/**
 * Shop vernacular per model, folded into the command palette's haystack.
 *
 * Exhaustive by type, so a new tool cannot ship without one.
 */
import type { ToolId } from "@/lib/catalog-tools";

export const toolAliases: Record<ToolId, string[]> = {
  pitchCircle: ["pcd", "pitch circle", "bolt circle", "bolt pattern", "hole coordinates", "hole circle"],
  regularPolygon: ["regular polygon", "polygon area", "apothem", "circumradius", "interior angle"],
  eccentricBoltGroup: ["bolt group", "eccentric bolt", "bolt pattern shear", "bolt circle load", "torsional shear"],
  pinStress: ["pin shear", "dowel pin", "pin bearing stress", "projected bearing", "clevis pin"],
  gearToothStress: ["gear tooth stress", "lewis equation", "gear bending", "spur gear tooth", "helical gear tooth", "virtual teeth", "gear root stress"],
  vacuumEvacuation: ["vacuum flow", "evacuation time", "pumpdown", "pump down", "vacuum chamber", "effective pumping speed", "required vacuum flow"],
  toggleForce: ["over center", "over-centre", "toggle", "toggle joint", "linkage force", "toggle force", "mechanical advantage", "knee lever"],
  wristInertia: ["wrist inertia", "tool inertia", "eoat inertia", "robot wrist", "parallel axis", "payload inertia", "flange inertia"],
  cycleBuilder: ["cycle builder", "machine cycle", "cycle time builder", "step time", "ordered steps", "throughput", "sequence time"],
  pneumaticLineLoss: ["pneumatic pressure drop", "compressed air pressure loss", "air line loss", "pneumatic pipe", "air pipe pressure drop", "Darcy air line"],
  tappingTorque: ["tapping torque", "tap torque", "thread tapping", "tapping power", "tap horsepower", "thread machining torque"],
  threadMachiningTime: ["thread time", "thread machining time", "threading time", "thread turning", "pitch feed", "thread cycle"],
  reynoldsNumber: ["reynolds number", "reynolds", "dimensionless flow", "hydraulic diameter", "dynamic viscosity", "kinematic viscosity"],
  minorLosses: ["minor losses", "minor loss", "loss coefficient", "k factor", "fitting loss", "local pressure loss", "sum k"],
  pipeSizing: ["pipe sizing", "pipe diameter", "velocity sizing", "target velocity", "flow diameter", "pipe flow", "pipe size", "size a pipe"],
  buoyancyForce: ["buoyancy", "buoyant force", "archimedes", "displaced volume", "floating force", "net buoyancy"],
  submergedPlane: ["center of pressure", "centre of pressure", "submerged plane", "hydrostatic force", "hydrostatic resultant", "vertical rectangle"],
  convectionHeat: ["convection", "convective heat", "heat transfer coefficient", "h a delta t", "heat rate", "cooling load"],
  thermalResistance: ["thermal resistance", "thermal network", "series resistance", "contact resistance", "wall resistance", "convection resistance"],
  idealGas: ["ideal gas", "gas density", "pv nrt", "molar density", "gas state", "specific volume"],
  isentropicMachine: ["isentropic", "compressor power", "turbine power", "pressure ratio", "isentropic efficiency", "gas compression"],
  gaugeBiasStudy: ["gage bias", "gauge bias", "linearity", "stability", "measurement bias", "measurement drift", "calibration bias"],
  controlChart: ["control chart", "x bar r", "xbar r", "x bar s", "xbar s", "individuals chart", "moving range", "i mr", "imr"],
  additiveBuild: ["additive manufacturing", "3d print", "print time", "print cost", "material volume", "support estimate"],
  gravityMoment: ["over center", "gravity moment", "lever moment", "static moment", "counter moment", "linkage gravity"],
  pneumaticCycleTime: ["pneumatic cycle", "cylinder time", "air cylinder speed", "pneumatic timing"],
  valveCv: ["valve cv", "flow coefficient", "water cv", "liquid valve", "valve sizing", "cv sizing", "control valve"],
  vacuumHolding: ["vacuum force", "suction cup", "vacuum holding", "gripper vacuum"],
  fixtureClamping: ["fixture force", "clamping force", "workholding", "fixture clamp"],
  pickPlaceCycle: ["pick place", "pick and place", "robot cycle", "cycle time", "throughput"],
  payloadInertia: ["payload inertia", "robot inertia", "eoat inertia", "tool payload"],
  sCurveProfile: ["s curve", "s-curve", "jerk limited", "jerk percent", "motion profile"],
  torqueSpeedDuty: ["torque speed", "duty point", "acceleration torque", "motor duty"],
  planetaryGear: ["planetary gear", "epicyclic", "sun ring carrier", "planet gear ratio"],
  wormDrive: ["worm gear", "worm drive", "worm ratio", "worm output torque"],
  fatigueConcentration: ["fatigue stress concentration", "kf", "kt", "notch sensitivity"],
  goodmanFatigue: ["goodman", "fatigue screen", "mean stress", "alternating stress"],
  minerDamage: ["miner rule", "miner damage", "cumulative fatigue", "palmgren miner"],
  cuttingPower: ["cutting power", "turning power", "specific cutting force", "machine power"],
  drillPointDepth: ["drill point", "drill tip depth", "programmed drill depth", "included angle"],
  toolDeflection: ["tool deflection", "cutter deflection", "cantilever tool", "tool bending"],
  ballScrewSizing: ["ball screw", "ballscrew", "screw torque", "linear screw speed", "screw drive force"],
  rackPinion: ["rack pinion", "rack and pinion", "pinion torque", "rack force", "rack speed"],
  beltAxis: ["belt axis", "timing belt axis", "belt drive torque", "linear belt", "pulley speed"],
  orientationControl: ["parallelism", "perpendicularity", "angularity", "orientation tolerance", "datum orientation"],
  profileRunout: ["profile", "circular runout", "total runout", "indicator variation", "tir"],
  processPerformance: ["pp", "ppk", "ppl", "ppu", "overall capability", "process performance"],
  hydraulicCylinder: ["hydraulic cylinder", "cylinder force", "cylinder speed", "cylinder time", "cylinder flow"],
  hydraulicPump: ["hydraulic pump", "pump displacement", "pump flow", "hydraulic horsepower", "pump torque"],
  hydraulicMotor: ["hydraulic motor", "motor torque", "motor speed", "motor displacement", "fluid motor"],
  hydraulicLine: ["hydraulic line", "hydraulic hose", "line velocity", "oil velocity", "pipe velocity"],
  shaftCombined: ["shaft bending torsion", "combined shaft loading", "von mises shaft", "shaft stress"],
  mohrCircle: ["mohr circle", "plane stress", "stress transformation", "principal stress", "maximum shear"],
  pressFit: ["interference fit", "press fit", "shrink fit", "contact pressure", "holding torque"],
  jointSeparation: ["joint separation", "bolted joint", "joint stiffness", "clamp force", "bolt member stiffness"],
  axial: ["tension", "compression", "stress", "strain", "elongation"], beam: ["bending", "deflection", "cantilever", "reaction", "beam deflection", "simply supported", "beam bending"], stability: ["buckling", "column", "euler", "column buckling", "euler buckling", "critical load"], section: ["moment of inertia", "area", "section modulus"], converter: ["units", "conversion", "convert", "unit converter", "converter", "unit conversion"], triangle: ["pythagoras", "right angle"], coordinate: ["distance", "point", "vector"], cylinder: ["volume", "surface area"], density: ["specific gravity", "mass", "volume"], newton: ["f ma", "force", "acceleration"], kinetic: ["energy", "momentum", "velocity"], hydrostatic: ["head", "liquid", "gauge pressure"], continuity: ["flow rate", "velocity", "pipe flow", "flow rate", "volumetric flow", "continuity equation"], sensibleHeat: ["calorimetry", "heat capacity", "thermal energy"], ohm: ["resistor", "voltage", "current", "power", "ohms law", "ohm's law", "ohm law"], fits: ["iso 286", "hole", "shaft", "clearance", "interference", "shaft hole fit", "clearance fit", "interference fit"], toleranceStack: ["rss", "worst case", "stackup"], position: ["true position", "gdt", "gd&t"], mmc: ["maximum material condition", "virtual condition", "bonus tolerance"], motionProfile: ["trapezoid", "triangular", "acceleration"], reflectedInertia: ["gearbox", "gear ratio", "motor inertia"], pneumatic: ["air cylinder", "bore", "retract"], clampForce: ["linkage", "clamp", "actuator"], torsion: ["shaft", "twist", "shear stress"], bearingLife: ["l10", "bearing", "rating life"], boltPreload: ["bolt", "fastener", "preload", "torque coefficient", "nut factor", "bolt torque", "tightening torque", "torque spec"], millingMrr: ["mrr", "machining", "material removal"], lmtd: ["heat exchanger", "log mean", "thermal"], darcy: ["darcy weisbach", "friction", "pipe loss"], thermalExpansion: ["cte", "coefficient of thermal expansion", "temperature growth", "thermal growth"], thermalStress: ["thermal stress", "restrained expansion", "temperature stress"], planeConduction: ["wall conduction", "thermal resistance", "fourier law", "heat flux"], bernoulli: ["bernoulli equation", "ideal flow", "flow energy", "pressure change"], combinedStress: ["von mises", "principal stress", "mohr circle", "bending torsion"], thinVessel: ["pressure vessel", "hoop stress", "longitudinal stress", "cylinder pressure"], leadScrew: ["power screw", "linear motion", "screw torque", "travel"], airConsumption: ["free air", "air use", "cylinder consumption", "nl/min"], gearRatio: ["spur gear", "reduction", "speed ratio", "gearbox"], boltLoad: ["bolt stress", "bolt shear", "bolt tension", "bearing stress", "washer stress"], safetyMargin: ["safety factor", "fos", "margin", "utilization", "allowable stress", "factor of safety", "safety margin"], circularArc: ["arc length", "chord", "segment area", "circle"], compressionSpring: ["spring rate", "coil spring", "wire diameter", "spring index", "deflection"], drillingTime: ["drilling", "machining time", "cutting speed", "spindle feed", "holes"], turningMrr: ["turning", "lathe", "mrr", "cutting speed", "feed per rev"], processCapability: ["cp", "cpk", "process capability", "specification limits", "six sigma"], extensionSpring: ["extension spring", "initial tension", "spring force", "spring rate"], torsionSpring: ["torsion spring", "angular rate", "spring moment", "coil bending stress"], keyway: ["keyway", "parallel key", "key shear", "key bearing", "shaft key"], cuttingParameters: ["milling rpm", "cutting speed", "feed rate", "chip load", "machining power", "specific cutting force", "feeds and speeds", "speeds and feeds", "feeds", "speeds"], sheetMetalBend: ["bend allowance", "bend deduction", "k factor", "flat pattern", "sheet metal"], productionMetrics: ["oee", "takt time", "throughput", "capacity", "labor content", "machine utilization"], gageRr: ["gage r&r", "gauge r&r", "measurement system", "repeatability", "reproducibility", "anova"], measurementUncertainty: ["measurement uncertainty", "expanded uncertainty", "coverage factor", "combined standard uncertainty", "rss uncertainty"], thermalRadiation: ["thermal radiation", "stefan boltzmann", "emissivity", "radiant heat", "radiative exchange"], shaftDesign: ["shaft sizing", "shaft deflection", "critical speed", "shaft twist", "solid shaft", "diameter"], bearingLoad: ["equivalent bearing load", "dynamic load rating", "static safety bearing", "bearing dn", "bearing preload"], formControl: ["flatness", "straightness", "circularity", "roundness", "cylindricity", "form tolerance"], driveRatio: ["spur gear", "helical gear", "worm gear", "belt drive", "timing belt", "chain drive", "gear force", "gear ratio"], motionDuty: ["motion sizing", "acceleration torque", "rms torque", "peak torque", "regenerative energy", "cycle time", "servo sizing", "stepper sizing"], filletWeld: ["fillet weld", "weld throat", "weld size", "weld stress", "weld length", "weld heat input"], threadDesign: ["tap drill", "thread engagement", "thread pull out", "thread stripping", "metric thread", "pilot hole"], orificeFlow: ["orifice flow", "orifice plate", "discharge coefficient", "pressure drop", "flow meter", "nozzle flow"], dimensionCheck: ["dimensional analysis", "dimension check", "unit consistency", "base dimensions", "formula check"], arithmeticScratchpad: ["engineering calculator", "arithmetic", "expression", "formula scratchpad", "pemdas"],
  toleranceSampling: ["monte carlo", "tolerance sampling", "seeded simulation", "statistical stack", "uniform tolerance", "distribution sample"],
  taylorToolLife: ["taylor tool life", "tool life", "cutting speed tool life", "v t n c", "taylor equation", "machining wear"],
  cuttingForce: ["cutting force", "specific cutting force", "uncut chip area", "cutting power", "turning force", "machining force"],
  weldGroup: ["weld group", "weld torsion", "weld line load", "direct shear weld", "fillet weld group", "eccentric weld"],
  beamDiagram: ["beam diagram", "shear diagram", "bending moment diagram", "simply supported beam", "beam reactions", "uniform load beam"],
  triangleTruss: ["triangle truss", "truss analysis", "method of joints", "truss reaction", "truss member force", "pin jointed truss"],
  hertzContact: ["hertz contact", "contact stress", "sphere on flat", "hertzian pressure", "elastic contact", "contact radius"],
  fractureIntensity: ["fracture mechanics", "stress intensity", "mode i", "lefm", "crack intensity", "geometry factor", "toughness ratio"],
  deflectionCheck: ["deflection limit", "deflection check", "span deflection", "l over", "l/360", "reference deflection", "deflection ratio"],
  bearingAdjustedLife: ["bearing adjusted life", "bearing life factor", "reliability factor", "material factor", "l10 adjustment", "rating life hours"],
  flywheelEnergy: ["flywheel energy", "rotational energy", "rotating inertia", "energy change", "kinetic energy flywheel", "rpm energy"],
  frictionClutch: ["clutch torque", "brake torque", "friction clutch", "disc brake", "friction interface", "clamp force torque"],
  splineLoad: ["spline load", "spline tooth", "spline pressure", "spline torque", "flank pressure", "splined shaft"],
  gearMeshForce: ["gear force", "mesh force", "helical force", "spur force", "tangential force", "radial force", "axial force"],
  beltTension: ["belt tension", "chain tension", "driving tension", "tight side", "loose side", "pulley torque tension"],
  vesselGeometry: ["vessel geometry", "cylinder volume", "pressure vessel volume", "shell volume", "wetted area", "cylindrical vessel"],
  threadTensileArea: ["thread tensile area", "bolt stress area", "fastener tensile area", "metric thread area", "external thread", "thread geometry"],
  couplingTorsion: ["coupling torsion", "coupling stiffness", "torsional stiffness", "coupling twist", "shaft coupling", "torsional energy"],
  cantileverFrame: ["cantilever frame", "frame equilibrium", "fixed base frame", "lateral frame load", "base moment", "base shear"],
  plateBuckling: ["plate buckling", "unstiffened plate", "critical buckling stress", "simply supported plate", "elastic plate stability", "buckling coefficient"],
  screwCriticalSpeed: ["screw critical speed", "ball screw critical speed", "lead screw critical speed", "screw rpm", "screw whip", "unsupported screw length"],
  linearGuideLife: ["linear guide life", "linear bearing life", "rail life", "lm guide nominal life", "dynamic load rating travel", "guide L10"],
  brakingDuty: ["braking resistor", "dynamic braking", "regenerative braking", "brake duty", "brake resistor wattage", "braking current"],
  ballScrewLife: ["ball screw life", "ballscrew life", "ball nut life", "ball screw L10", "screw travel life", "axial rating life"],
  driveTrain: ["drive train", "drivetrain efficiency", "multi stage gearbox", "series gear train", "gear train loss", "multi-stage reduction"],
  rmsDutyTorque: ["RMS torque", "duty torque", "servo RMS", "motor duty cycle", "three segment torque", "root mean square torque"],
  motorOperatingPoint: ["motor operating point", "servo motor power", "stepper motor power", "AC motor power", "motor torque speed power", "shaft operating point", "motor sizing", "size a motor"],
  gripperHold: ["gripper force", "parallel gripper", "EOAT gripping force", "friction grip", "jaw force", "robot gripper hold"],
  conveyorLine: ["conveyor line speed", "conveyor throughput", "containers per minute", "product pitch", "conveyor rate", "items per minute"],
  robotReach: ["robot reach", "robot envelope", "radial reach", "robot target distance", "robot workspace screen"],
  robotPayloadMoment: ["robot payload moment", "robot CoG moment", "flange moment", "robot base load", "payload offset"],
  rotaryIndexing: ["rotary index table", "indexing table motion", "dial table", "rotary indexer", "index time"],
  pneumaticDemandBudget: ["pneumatic demand", "air demand budget", "compressed air budget", "normalized air flow", "compressor flow reference", "FRL flow reference"],
  hydraulicLossBudget: ["hydraulic loss power", "hydraulic pressure drop power", "hydraulic heat load", "oil power loss", "pressure drop budget", "hydraulic circuit power"],
  vacuumLeakageBudget: ["vacuum leakage", "vacuum leak budget", "suction flow reference", "vacuum demand", "leakage flow", "vacuum generator reference"],
  hydraulicAccumulatorState: ["hydraulic accumulator", "accumulator gas", "precharge gas volume", "polytropic accumulator", "usable accumulator volume", "bladder accumulator state"],
  hydraulicReservoirDwell: ["hydraulic reservoir", "hydraulic tank", "reservoir dwell time", "oil residence time", "tank volume flow", "reservoir volume"],
  darcyFrictionFactor: ["Darcy friction factor", "Swamee Jain", "Colebrook approximation", "pipe roughness", "relative roughness", "Moody friction factor"],
  pumpSystemHeadPoint: ["pump system curve", "system head", "static head", "quadratic loss", "system curve point", "pump head requirement"],
  npshAvailableBudget: ["NPSH available", "NPSHa", "suction head budget", "vapor pressure head", "pump suction", "NPSH required reference"],
  thermalRcStep: ["thermal RC", "thermal time constant", "lumped thermal transient", "temperature step response", "thermal capacitance", "thermal resistance"],
  manningUniformFlow: ["Manning equation", "open channel flow", "uniform flow", "channel discharge", "hydraulic radius", "Manning roughness"],
  compressibleMassFlow: ["compressible mass flow", "isentropic mass flow", "Mach mass flow", "gas mass flow", "NASA mass flow", "choked flow relation"],
  machiningTimeBudget: ["machining time", "cycle time", "cutting length", "feed rate", "CNC time", "cut time"],
  threePhasePower: ["three phase power", "three phase kVA", "three phase kW", "line voltage current", "apparent power", "power factor"],
  sheetBendAllowance: ["bend allowance", "bend deduction", "sheet metal bend", "K factor", "flat pattern bend", "neutral axis"],
  idealGasEntropyChange: ["ideal gas entropy", "entropy change", "specific entropy", "constant cp entropy", "temperature pressure entropy", "NASA entropy"],
  gravitationalPe: ["potential energy", "gravitational energy", "mgh", "elevation energy", "datum energy"],
  pipeVelocity: ["pipe velocity", "mean velocity", "continuity velocity", "pipe flow speed", "inside diameter velocity"],
  dynamicPressure: ["dynamic pressure", "stagnation", "q pressure", "wind pressure", "½ρv²", "half rho v squared"],
};
