/**
 * Which tool ids are answered by a library document.
 *
 * Deliberately just the names. `computeTool` in engineering.ts asks this
 * before anything else, and 33 of these ids also have a hand-written
 * implementation further down the same if-chain — dead code today, because the
 * document branch is first and wins.
 *
 * That is why this list cannot be "which documents have been fetched". Once
 * documents load per domain, a lookup against the loaded map would answer false
 * for a model whose domain had not arrived yet, the chain would fall through,
 * and those 33 tools would quietly run a different implementation and return a
 * different number. Not an error — a wrong answer, silently, on a page that
 * looks entirely normal.
 *
 * So membership is static and loading is separate: if the id is here the
 * document branch is taken, and if the document is missing `runLibraryDocument`
 * throws with the model's own name rather than guessing.
 *
 * Regenerate with:
 *
 *   node --experimental-strip-types --import ./scripts/alias-register.mjs -e 'import("@/lib/document-library").then(m=>console.log(Object.keys(m.libraryDocuments).sort().map(i=>JSON.stringify(i)).join(",")))'
 *
 * Generated from document-library.ts. `document-tool-ids.test.mjs` asserts it
 * still matches, so adding a model without regenerating fails a test instead of
 * silently routing that model to the wrong implementation.
 */
export const DOCUMENT_TOOL_IDS: ReadonlySet<string> = new Set([
  "additiveBuild",
  "airConsumption",
  "axial",
  "ballScrewLife",
  "ballScrewSizing",
  "beam",
  "bearingAdjustedLife",
  "bearingLife",
  "bearingLoad",
  "beltAxis",
  "beltTension",
  "bernoulli",
  "boltLoad",
  "boltPreload",
  "brakingDuty",
  "buoyancyForce",
  "cantileverFrame",
  "circularArc",
  "clampForce",
  "combinedStress",
  "compressibleMassFlow",
  "compressionSpring",
  "continuity",
  "convectionHeat",
  "conveyorLine",
  "coordinate",
  "couplingTorsion",
  "cuttingForce",
  "cuttingParameters",
  "cuttingPower",
  "cylinder",
  "darcy",
  "darcyFrictionFactor",
  "deflectionCheck",
  "density",
  "dimensionCheck",
  "drillPointDepth",
  "drillingTime",
  "driveRatio",
  "driveTrain",
  "dynamicPressure",
  "eccentricBoltGroup",
  "extensionSpring",
  "fatigueConcentration",
  "filletWeld",
  "fixtureClamping",
  "flywheelEnergy",
  "formControl",
  "fractureIntensity",
  "frictionClutch",
  "gageRr",
  "gearMeshForce",
  "gearRatio",
  "gearToothStress",
  "goodmanFatigue",
  "gravitationalPe",
  "gravityMoment",
  "gripperHold",
  "hertzContact",
  "hydraulicAccumulatorState",
  "hydraulicCylinder",
  "hydraulicLine",
  "hydraulicLossBudget",
  "hydraulicMotor",
  "hydraulicPump",
  "hydraulicReservoirDwell",
  "hydrostatic",
  "idealGas",
  "idealGasEntropyChange",
  "isentropicMachine",
  "jointSeparation",
  "keyway",
  "kinetic",
  "leadScrew",
  "linearGuideLife",
  "lmtd",
  "machiningTimeBudget",
  "manningUniformFlow",
  "measurementUncertainty",
  "millingMrr",
  "minerDamage",
  "minorLosses",
  "mmc",
  "mohrCircle",
  "motionDuty",
  "motionProfile",
  "motorOperatingPoint",
  "newton",
  "npshAvailableBudget",
  "ohm",
  "orientationControl",
  "orificeFlow",
  "payloadInertia",
  "pickPlaceCycle",
  "pinStress",
  "pipeSizing",
  "pipeVelocity",
  "pitchCircle",
  "planeConduction",
  "planetaryGear",
  "plateBuckling",
  "pneumatic",
  "pneumaticCycleTime",
  "pneumaticDemandBudget",
  "pneumaticLineLoss",
  "position",
  "pressFit",
  "processCapability",
  "productionMetrics",
  "profileRunout",
  "pumpSystemHeadPoint",
  "rackPinion",
  "reflectedInertia",
  "regularPolygon",
  "reynoldsNumber",
  "rmsDutyTorque",
  "robotPayloadMoment",
  "robotReach",
  "rotaryIndexing",
  "sCurveProfile",
  "safetyMargin",
  "screwCriticalSpeed",
  "sensibleHeat",
  "shaftCombined",
  "shaftDesign",
  "sheetBendAllowance",
  "sheetMetalBend",
  "splineLoad",
  "stability",
  "submergedPlane",
  "tappingTorque",
  "taylorToolLife",
  "thermalExpansion",
  "thermalRadiation",
  "thermalRcStep",
  "thermalResistance",
  "thermalStress",
  "thinVessel",
  "threadDesign",
  "threadMachiningTime",
  "threadTensileArea",
  "threePhasePower",
  "toggleForce",
  "toleranceStack",
  "toolDeflection",
  "torqueSpeedDuty",
  "torsion",
  "torsionSpring",
  "triangle",
  "triangleTruss",
  "turningMrr",
  "vacuumEvacuation",
  "vacuumHolding",
  "vacuumLeakageBudget",
  "valveCv",
  "vesselGeometry",
  "weldGroup",
  "wormDrive",
  "wristInertia",
]);
