// Generated by scripts/generate-home-demo.mjs. Do not edit.
//
// The front page's worked example, taken from the axial model itself so
// the numbers on the door are the numbers the calculator produces.
// `npm test` fails if this drifts.

export type HomeDemo = {
  toolId: string;
  title: string;
  inputs: { label: string; value: string; unit: string }[];
  outputs: { label: string; display: string; unit: string }[];
  formula: string;
  assumptions: string[];
  boundary: string;
  sourceLabel: string;
  sourceUrl: string;
};

export const homeDemo: HomeDemo = {
  "toolId": "axial",
  "title": "Axial response",
  "inputs": [
    {
      "label": "Axial load",
      "value": "10",
      "unit": "kN"
    },
    {
      "label": "Cross-sectional area",
      "value": "1000",
      "unit": "mm²"
    },
    {
      "label": "Original length",
      "value": "1000",
      "unit": "mm"
    },
    {
      "label": "Elastic modulus",
      "value": "200",
      "unit": "GPa"
    }
  ],
  "outputs": [
    {
      "label": "Average normal stress",
      "display": "10",
      "unit": "MPa"
    },
    {
      "label": "Elastic strain",
      "display": "50",
      "unit": "µε"
    },
    {
      "label": "Ideal length change",
      "display": "0.05",
      "unit": "mm"
    }
  ],
  "formula": "σ = F / A · ε = σ / E · ΔL = FL / AE",
  "assumptions": [
    "Uniform cross-section",
    "Axial loading",
    "Linear-elastic response"
  ],
  "boundary": "Not a local peak, not a connection, not a code check.",
  "sourceLabel": "Boston University mechanics notes",
  "sourceUrl": "https://www.bu.edu/moss/mechanics-of-materials-axial-load/"
};
