import type { InstrumentDocument } from "@/lib/document";

/** Leftover Band-1 algebra. Shop units stay on the glass; kit cannot convert every quantity yet. */
export const leftoverDocuments: Record<string, InstrumentDocument> = {
  reflectedInertia: {
    slug: "reflectedInertia",
    title: "Reflected inertia",
    description: "Reflect a stated load inertia through one ideal reduction ratio and compare it with a stated motor inertia.",
    domain: "automation",
    fields: [
      { id: "loadInertia", label: "Load inertia", symbol: "JL", help: "Stated inertia at the driven side of the ideal reduction.", defaultValue: 0.08, defaultUnit: "kg·m²" },
      { id: "gearRatio", label: "Reduction ratio", symbol: "N", help: "Driven speed divided by motor speed is 1/N; enter N > 1 for reduction.", defaultValue: 5, defaultUnit: ":1" },
      { id: "motorInertia", label: "Motor inertia", symbol: "JM", help: "Rotor inertia for the stated motor condition.", defaultValue: 0.002, defaultUnit: "kg·m²" },
    ],
    outputs: [
      { id: "reflected", label: "Reflected load inertia", defaultUnit: "kg·m²", expression: "loadInertia/gearRatio^2" },
      { id: "inertiaRatio", label: "Reflected-to-motor inertia ratio", defaultUnit: "—", expression: "(loadInertia/gearRatio^2)/motorInertia" },
      { id: "total", label: "Motor-side total inertia", defaultUnit: "kg·m²", expression: "loadInertia/gearRatio^2+motorInertia" },
    ],
    formula: "Jref = JL / N² · Jtotal = JM + Jref",
    purpose: "Reflect a stated load inertia through one ideal reduction ratio and compare it with a stated motor inertia.",
    assumptions: ["Ideal rigid transmission","One reduction ratio","Constant inertias"],
    boundary: "Not a design stamp. Use only inside the stated model boundary.",
    interpretation: "Reflected inertia · inertia ratio",
    sourceLabel: "Reflected-inertia reference",
    sourceUrl: "https://www.motioncontroltips.com/how-do-gearmotors-impact-reflected-mass-inertia-from-the-load/",
    related: [],
    warnings: ["This reflects one rigid load through one ideal ratio. It excludes gearbox inertia, efficiency, backlash, compliance, duty cycle, peak torque, motor control behavior, and any motor-selection decision."],
  },
  convectionHeat: {
    slug: "convectionHeat",
    title: "Convection heat rate",
    description: "Calculate heat rate from a user-entered convection coefficient, effective area, and signed temperature difference.",
    domain: "thermal",
    fields: [
      { id: "coefficient", label: "Declared convection coefficient", symbol: "h", help: "User-entered heat-transfer coefficient for the stated setup; this workspace does not derive a correlation.", defaultValue: 35, defaultUnit: "W/(m²·K)" },
      { id: "area", label: "Declared heat-transfer area", symbol: "A", help: "User-entered effective area; geometry and fin efficiency are excluded.", defaultValue: 1.8, defaultUnit: "m²" },
      { id: "deltaT", label: "Declared temperature difference", symbol: "ΔT", help: "User-entered signed bulk-to-surface temperature difference; no temperature field is derived.", defaultValue: 25, defaultUnit: "K", signed: true },
    ],
    outputs: [
      { id: "heatRate", label: "Declared convection heat rate", defaultUnit: "W", expression: "coefficient*area*deltaT" },
      { id: "heatRateKw", label: "Declared convection heat rate", defaultUnit: "kW", expression: "coefficient*area*deltaT/1000" },
      { id: "conductance", label: "Declared convection conductance hA", defaultUnit: "W/K", expression: "coefficient*area" },
    ],
    formula: "Q̇ = hAΔT",
    purpose: "Calculate heat rate from a user-entered convection coefficient, effective area, and signed temperature difference.",
    assumptions: ["User-entered convection coefficient","Declared effective area","Declared signed temperature difference","Steady scalar arithmetic"],
    boundary: "Not a design stamp. Use only inside the stated model boundary.",
    interpretation: "Heat rate · heat rate in kW · convection conductance",
    sourceLabel: "DOE Convection Heat Transfer handbook",
    sourceUrl: "https://engineeringlibrary.org/reference/convection-heat-transfer-doe-handbook",
    related: [],
    warnings: ["This is user-entered convection coefficient arithmetic only. It does not derive a heat-transfer coefficient or correlation, determine flow regime, calculate a temperature field, model radiation, conduction, phase change, fins, contact resistance, material selection, service-temperature rating, equipment suitability, safety, or approval."],
  },
  wristInertia: {
    slug: "wristInertia",
    title: "Wrist & tool inertia",
    description: "Calculate a declared one-axis wrist/tool inertia from EOAT and payload mass, centroidal inertia, and independent flange-axis offsets.",
    domain: "automation",
    fields: [
      { id: "eoatMass", label: "Declared EOAT mass", symbol: "mₑ", help: "Mass of the declared end-of-arm tooling body only.", defaultValue: 5, defaultUnit: "kg", signed: true },
      { id: "eoatCentroidalInertia", label: "Declared EOAT centroidal inertia", symbol: "Iₑ,cg", help: "User-entered EOAT mass moment of inertia about the stated parallel centroidal axis.", defaultValue: 0.02, defaultUnit: "kg·m²", signed: true },
      { id: "eoatOffset", label: "EOAT flange-axis offset", symbol: "rₑ", help: "Perpendicular distance from the stated flange/wrist axis to the EOAT centre of mass.", defaultValue: 0.15, defaultUnit: "m", signed: true },
      { id: "payloadMass", label: "Declared payload mass", symbol: "mₚ", help: "Mass of the declared carried part or process payload.", defaultValue: 2, defaultUnit: "kg", signed: true },
      { id: "payloadCentroidalInertia", label: "Declared payload centroidal inertia", symbol: "Iₚ,cg", help: "User-entered payload mass moment of inertia about the stated parallel centroidal axis.", defaultValue: 0.005, defaultUnit: "kg·m²", signed: true },
      { id: "payloadOffset", label: "Payload flange-axis offset", symbol: "rₚ", help: "Perpendicular distance from the stated flange/wrist axis to the payload centre of mass.", defaultValue: 0.3, defaultUnit: "m", signed: true },
    ],
    outputs: [
      { id: "totalMass", label: "Declared EOAT + payload mass", defaultUnit: "kg", expression: "eoatMass+payloadMass" },
      { id: "eoatAxisInertia", label: "EOAT inertia about stated wrist axis", defaultUnit: "kg·m²", expression: "eoatCentroidalInertia+eoatMass*eoatOffset^2" },
      { id: "payloadAxisInertia", label: "Payload inertia about stated wrist axis", defaultUnit: "kg·m²", expression: "payloadCentroidalInertia+payloadMass*payloadOffset^2" },
      { id: "totalInertia", label: "Declared total wrist/tool inertia", defaultUnit: "kg·m²", expression: "eoatCentroidalInertia+eoatMass*eoatOffset^2+payloadCentroidalInertia+payloadMass*payloadOffset^2" },
    ],
    formula: "Iaxis = Icg + mr² · Itotal = IEOAT,axis + Ipayload,axis",
    purpose: "Calculate a declared one-axis wrist/tool inertia from EOAT and payload mass, centroidal inertia, and independent flange-axis offsets.",
    assumptions: ["One declared parallel rotation axis","User-entered centroidal inertias","User-entered flange-axis offsets","Rigid lumped EOAT and payload bodies"],
    boundary: "Not a design stamp. Use only inside the stated model boundary.",
    interpretation: "EOAT inertia · payload inertia · total wrist inertia",
    sourceLabel: "Engineering Statics parallel-axis theorem",
    sourceUrl: "https://engineeringstatics.org/parallel-axis-theorem-section.html",
    related: [],
    warnings: ["This is a one-axis, user-entered parallel-axis inertia sum for two rigid declared bodies. It does not construct an inertia tensor, infer geometry, identify a robot axis, calculate motion dynamics, establish payload/reach/duty limits, validate collision, select hardware, establish safety, or approve a robot cell."],
  },
  couplingTorsion: {
    slug: "couplingTorsion",
    title: "Declared coupling torsion",
    description: "Calculate the elastic twist and stored energy from a user-entered coupling torque and torsional stiffness without selecting or qualifying a coupling.",
    domain: "mechanics",
    fields: [
      { id: "torque", label: "Declared transmitted torque", symbol: "T", help: "User-entered torque at the stated coupling operating point; transient duty is excluded.", defaultValue: 250, defaultUnit: "N·m" },
      { id: "torsionalStiffness", label: "Declared torsional stiffness", symbol: "kt", help: "User-entered linear coupling torsional stiffness; geometry and supplier data are not inferred.", defaultValue: 12000, defaultUnit: "N·m/rad" },
    ],
    outputs: [
      { id: "twistRad", label: "Declared elastic twist", defaultUnit: "rad", expression: "torque/torsionalStiffness" },
      { id: "twistDeg", label: "Declared elastic twist", defaultUnit: "deg", expression: "torque/torsionalStiffness*180/pi" },
      { id: "storedEnergy", label: "Linear elastic stored energy", defaultUnit: "J", expression: "torque^2/(2*torsionalStiffness)" },
    ],
    formula: "θ = T/kt · U = T²/(2kt)",
    purpose: "Calculate the elastic twist and stored energy from a user-entered coupling torque and torsional stiffness without selecting or qualifying a coupling.",
    assumptions: ["Linear torsional stiffness","Declared transmitted torque","Small elastic twist","No dynamic model"],
    boundary: "Not a design stamp. Use only inside the stated model boundary.",
    interpretation: "Elastic twist · stored energy",
    sourceLabel: "SDP/SI coupling stiffness context",
    sourceUrl: "https://sdp-si.com/Rivin/art2.php",
    related: [],
    warnings: ["This is declared linear torsional stiffness arithmetic for a coupling. It excludes coupling selection, torque capacity, flexible-element geometry, fatigue, resonance, damping, misalignment, shaft/bearing loads, safety, and approval."],
  },
  fractureIntensity: {
    slug: "fractureIntensity",
    title: "Mode-I fracture intensity",
    description: "Calculate one declared Mode-I linear-elastic stress intensity and its ratio to a user-entered toughness reference without interpreting crack behavior.",
    domain: "mechanics",
    fields: [
      { id: "geometryFactor", label: "Declared Mode-I geometry factor", symbol: "Y", help: "User-entered dimensionless factor from a geometry-specific validated source; this workspace does not select it.", defaultValue: 1.12, defaultUnit: "—" },
      { id: "tensileStress", label: "Declared remote tensile stress", symbol: "σ", help: "User-entered nominal tensile stress in the stated linear-elastic model.", defaultValue: 100, defaultUnit: "MPa" },
      { id: "crackHalfLength", label: "Declared crack half-length", symbol: "a", help: "User-entered half crack length for the geometry-factor definition.", defaultValue: 5, defaultUnit: "mm" },
      { id: "toughnessReference", label: "Declared toughness reference", symbol: "KIC", help: "User-entered reference used only for literal ratio arithmetic; no fracture conclusion is made.", defaultValue: 50, defaultUnit: "MPa√m" },
    ],
    outputs: [
      { id: "stressIntensity", label: "Mode-I stress intensity", defaultUnit: "MPa√m", expression: "geometryFactor*tensileStress*sqrt(pi*crackHalfLength/1000)" },
      { id: "toughnessRatio", label: "Intensity / declared toughness reference", defaultUnit: "—", expression: "geometryFactor*tensileStress*sqrt(pi*crackHalfLength/1000)/toughnessReference" },
      { id: "arithmeticDifference", label: "Declared-reference minus intensity", defaultUnit: "MPa√m", expression: "toughnessReference-geometryFactor*tensileStress*sqrt(pi*crackHalfLength/1000)" },
    ],
    formula: "KI = Yσ√(πa) · ratio = KI / KIC,declared",
    purpose: "Calculate one declared Mode-I linear-elastic stress intensity and its ratio to a user-entered toughness reference without interpreting crack behavior.",
    assumptions: ["Mode-I opening loading","Declared geometry factor","Linear-elastic fracture-mechanics arithmetic","User-entered toughness reference"],
    boundary: "Not a design stamp. Use only inside the stated model boundary.",
    interpretation: "Stress intensity · toughness ratio · arithmetic margin",
    sourceLabel: "Applied Mechanics of Solids LEFM chapter",
    sourceUrl: "http://solidmechanics.org/Text/Chapter9_3/Chapter9_3.php",
    related: [],
    warnings: ["This is declared-geometry-factor Mode-I linear-elastic fracture-mechanics arithmetic. Stress intensity depends on detailed geometry and loading; this workspace does not infer a factor, establish LEFM applicability, determine fracture or crack growth, predict life, define inspection intervals, select a material, establish safety, or approve a design."],
  },
  jointSeparation: {
    slug: "jointSeparation",
    title: "Bolted-joint separation",
    description: "Estimate load sharing, residual clamp force, and a separation-load threshold from user-entered bolt/member stiffness and preload for one axial joint.",
    domain: "mechanics",
    fields: [
      { id: "preload", label: "Declared preload", symbol: "Fp", help: "Preload for one stated bolt/joint condition; uncertainty and loss are not modeled.", defaultValue: 20, defaultUnit: "kN" },
      { id: "boltStiffness", label: "Bolt axial stiffness", symbol: "kb", help: "User-entered equivalent axial bolt stiffness for the stated grip condition.", defaultValue: 150, defaultUnit: "kN/mm" },
      { id: "memberStiffness", label: "Member axial stiffness", symbol: "km", help: "User-entered equivalent axial clamped-member stiffness; geometry is not inferred.", defaultValue: 300, defaultUnit: "kN/mm" },
      { id: "externalLoad", label: "External axial separating load", symbol: "P", help: "Known applied separating load on this one joint; positive is separating and negative is compressive.", defaultValue: 18, defaultUnit: "kN", signed: true },
    ],
    outputs: [
      { id: "loadFraction", label: "Bolt load fraction C", defaultUnit: "%", expression: "boltStiffness/(boltStiffness+memberStiffness)*100" },
      { id: "boltLoadIncrease", label: "External-load share carried by bolt", defaultUnit: "kN", expression: "boltStiffness/(boltStiffness+memberStiffness)*externalLoad" },
      { id: "residualClamp", label: "Residual clamp force", defaultUnit: "kN", expression: "preload-(1-boltStiffness/(boltStiffness+memberStiffness))*externalLoad" },
      { id: "separationLoad", label: "Ideal separation-load threshold", defaultUnit: "kN", expression: "preload/(1-boltStiffness/(boltStiffness+memberStiffness))" },
      { id: "separationReserve", label: "Threshold minus stated external load", defaultUnit: "kN", expression: "preload/(1-boltStiffness/(boltStiffness+memberStiffness))-externalLoad" },
    ],
    formula: "C = kb/(kb+km) · ΔFb = CP · Fm = Fp−(1−C)P · Psep = Fp/(1−C)",
    purpose: "Estimate load sharing, residual clamp force, and a separation-load threshold from user-entered bolt/member stiffness and preload for one axial joint.",
    assumptions: ["One preloaded axial joint","User-entered stiffnesses","Linear parallel springs","Known external load"],
    boundary: "Not a design stamp. Use only inside the stated model boundary.",
    interpretation: "Load share · clamp force · separation threshold",
    sourceLabel: "Sandia bolted-joint guideline",
    sourceUrl: "https://engineeringlibrary.org/reference/bolted-joint-design-analysis-sandia",
    related: [],
    warnings: ["This is a one-bolt, axial, linear parallel-spring screen with user-entered equivalent stiffnesses. It does not infer stiffness from geometry, distribute a system load among bolts, account for preload variation or relaxation, nonlinear contact, shear, bending, thermal effects, fatigue, gasket behavior, joint slip, safety factors, or prove that a joint will not separate."],
  },
  rotaryIndexing: {
    slug: "rotaryIndexing",
    title: "Declared rotary indexing motion",
    description: "Calculate ideal average angular speed, literal move-only index rate, and rotational kinetic energy at that average speed from declared rotary-index-table motion inputs.",
    domain: "dynamics",
    fields: [
      { id: "indexAngle", label: "Declared index angle", symbol: "α", help: "User-entered angular displacement for one index; position accuracy and the motion profile are excluded.", defaultValue: 60, defaultUnit: "deg" },
      { id: "moveTime", label: "Declared move time", symbol: "tmove", help: "User-entered time for the index motion only; dwell and process timing are excluded.", defaultValue: 0.5, defaultUnit: "s" },
      { id: "systemInertia", label: "Declared table-plus-load inertia", symbol: "I", help: "User-entered rotational inertia about the declared indexing axis; geometry, gearing, and motor inertia are not derived.", defaultValue: 0.05, defaultUnit: "kg·m²" },
    ],
    outputs: [
      { id: "indexAngleRad", label: "Declared index angle in radians", defaultUnit: "rad", expression: "indexAngle*pi/180" },
      { id: "averageAngularSpeed", label: "Ideal average angular speed", defaultUnit: "rad/s", expression: "(indexAngle*pi/180)/moveTime" },
      { id: "indexesPerMinute", label: "Literal move-only index rate", defaultUnit: "indexes/min", expression: "60/moveTime" },
      { id: "kineticEnergy", label: "Rotational kinetic energy at average speed", defaultUnit: "J", expression: "0.5*systemInertia*((indexAngle*pi/180)/moveTime)^2" },
    ],
    formula: "θ = α·π/180 · ωavg = θ/tmove · rate(move-only) = 60/tmove · KE = ½Iωavg²",
    purpose: "Calculate ideal average angular speed, literal move-only index rate, and rotational kinetic energy at that average speed from declared rotary-index-table motion inputs.",
    assumptions: ["Declared index angle and move time","Declared table-plus-load inertia","Ideal average-speed relation","Move-only rate with no dwell"],
    boundary: "Not a design stamp. Use only inside the stated model boundary.",
    interpretation: "Average speed · index rate · kinetic energy",
    sourceLabel: "KEB rotary index table guidance",
    sourceUrl: "https://www.kebamerica.com/blog/how-do-i-size-a-motor-for-my-application-rotary-index-table/",
    related: [],
    warnings: ["This applies only declared index-angle, move-time, and table-plus-load-inertia arithmetic. It excludes acceleration profile, peak/RMS torque, friction, gearing, motor/table selection, capacity, position accuracy, dwell/process timing, safety, suitability, and approval."],
  },
  motionDuty: {
    slug: "motionDuty",
    title: "Motion duty & energy screen",
    description: "Calculate angular acceleration, inertia torque, duty-cycle RMS torque, total cycle time, and a kinetic regenerative-energy upper bound from declared motion conditions.",
    domain: "mechanics",
    fields: [
      { id: "reflectedInertia", label: "Total reflected inertia", symbol: "J", help: "User-entered total inertia referred to the stated motor/axis; no load inertia is inferred.", defaultValue: 0.012, defaultUnit: "kg·m²" },
      { id: "startSpeed", label: "Start speed", symbol: "n0", help: "Initial angular speed for the declared acceleration or deceleration interval.", defaultValue: 0, defaultUnit: "rpm", signed: true },
      { id: "endSpeed", label: "End speed", symbol: "n1", help: "Final angular speed for the declared acceleration or deceleration interval.", defaultValue: 1800, defaultUnit: "rpm", signed: true },
      { id: "accelTime", label: "Speed-change time", symbol: "tacc", help: "Time over which the stated speed change occurs.", defaultValue: 0.4, defaultUnit: "s" },
      { id: "constantTorque", label: "Declared running torque", symbol: "Trun", help: "User-entered torque magnitude during the constant-torque segment.", defaultValue: 1.8, defaultUnit: "N·m", signed: true },
      { id: "runningTime", label: "Running segment time", symbol: "trun", help: "Duration assigned to the declared running torque.", defaultValue: 1.2, defaultUnit: "s", signed: true },
      { id: "declaredDecelTorque", label: "Declared deceleration torque", symbol: "Tdec", help: "User-entered torque magnitude during the deceleration segment for RMS arithmetic.", defaultValue: 3.5, defaultUnit: "N·m", signed: true },
      { id: "decelTime", label: "Deceleration segment time", symbol: "tdec", help: "Duration assigned to the declared deceleration torque.", defaultValue: 0.4, defaultUnit: "s", signed: true },
    ],
    outputs: [
      { id: "angularAcceleration", label: "Angular acceleration", defaultUnit: "rad/s²", expression: "(endSpeed*2*pi/60-startSpeed*2*pi/60)/accelTime" },
      { id: "inertiaTorque", label: "Inertia acceleration torque", defaultUnit: "N·m", expression: "reflectedInertia*((endSpeed*2*pi/60-startSpeed*2*pi/60)/accelTime)" },
      { id: "totalCycleTime", label: "Declared total cycle time", defaultUnit: "s", expression: "accelTime+runningTime+decelTime" },
      { id: "rmsTorque", label: "Declared-duty RMS torque", defaultUnit: "N·m", expression: "sqrt(((reflectedInertia*((endSpeed*2*pi/60-startSpeed*2*pi/60)/accelTime))^2*accelTime+constantTorque^2*runningTime+declaredDecelTorque^2*decelTime)/(accelTime+runningTime+decelTime))" },
      { id: "recoverableKineticEnergyUpperBound", label: "Kinetic energy released if decelerating", defaultUnit: "J", expression: "max(0,0.5*reflectedInertia*((startSpeed*2*pi/60)^2-(endSpeed*2*pi/60)^2))" },
    ],
    formula: "α = (ω1−ω0)/tacc · Tacc = Jα · Trms = √(ΣTᵢ²tᵢ/Σtᵢ) · Ereleased = ½J(ω0²−ω1²)",
    purpose: "Calculate angular acceleration, inertia torque, duty-cycle RMS torque, total cycle time, and a kinetic regenerative-energy upper bound from declared motion conditions.",
    assumptions: ["User-entered reflected inertia","Piecewise constant torque segments","No inferred load/friction torque","Kinetic-energy upper bound"],
    boundary: "Not a design stamp. Use only inside the stated model boundary.",
    interpretation: "Acceleration · torque · RMS · cycle · energy",
    sourceLabel: "Oriental Motor motion sizing basics",
    sourceUrl: "https://blog.orientalmotor.com/motor-sizing-basics-part-3-acceleration-torque-and-rms-torque",
    related: [],
    warnings: ["This is declared-duty arithmetic: inertia acceleration torque from user-entered reflected inertia and speed change; RMS torque from three user-entered constant-torque segments; and a kinetic-energy upper bound only when the stated interval decelerates. It does not infer friction, gravity, cutting/process load, reflected inertia, motor capability, drive current, thermal limits, braking hardware, bus capacity, power regeneration, safety category, or motion-profile suitability."],
  },
};
