/**
 * GENERATED — do not edit by hand.
 * Run: node --experimental-strip-types --import ./scripts/alias-register.mjs scripts/build-formula-index.mjs
 *
 * The governing relation shown on each Library card, projected out of
 * `libraryDocuments` so the landing page does not import every document just to
 * render one line per model. `library-formulas.test.mjs` fails if this drifts
 * from the documents it came from.
 */
export const libraryFormulas: Record<string, string> = {
  "axial": "σ = F / A · ε = σ / E · ΔL = FL / AE",
  "newton": "Fnet = ma",
  "kinetic": "KE = ½mv² · p = mv",
  "ohm": "V = IR · P = VI = V²/R",
  "density": "ρ = m / V · v = 1 / ρ",
  "hydrostatic": "pg = ρgh",
  "continuity": "Q = A₁v₁ = A₂v₂",
  "sensibleHeat": "Q = mcΔT",
  "darcy": "Δp = f(L/D)(ρv²/2) · hL = Δp/(ρg)",
  "millingMrr": "MRR = ap·ae·Vf / 1,000",
  "turningMrr": "MRR = ap·f·Vc",
  "safetyMargin": "Factor = σallow/σapp · margin = factor − 1 · utilization = σapp/σallow",
  "cuttingForce": "Ac = ap·f · Fc = kc·Ac · Pideal = Fc·Vc/60,000",
  "thermalExpansion": "ΔL = αL₀ΔT · εth = αΔT",
  "thermalStress": "σth = EαΔT",
  "coordinate": "d = √[(x₂−x₁)² + (y₂−y₁)² + (z₂−z₁)²]",
  "cylinder": "V = π(D/2)²L · Aend = π(D/2)² · Alateral = πDL",
  "bernoulli": "p₁ + ½ρv₁² + ρgz₁ = p₂ + ½ρv₂² + ρgz₂",
  "pipeSizing": "D = √(4Q/(πvtarget)) · A = Q/vtarget",
  "valveCv": "Q = Cv√(ΔP/SG) · Cvrequired = Q√(SG/ΔP)",
  "planeConduction": "Q̇ = kA(Th − Tc)/L · Rth = L/(kA)",
  "minerDamage": "D = n1/N1 + n2/N2 + n3/N3",
  "extensionSpring": "F = Fi + kx",
  "position": "⌀ deviation = 2√(Δx² + Δy²)",
  "combinedStress": "σx = σa + σb · σ₁,₂ = σx/2 ± √[(σx/2)² + τxy²] · σvm = √(σx² + 3τxy²)",
  "rmsDutyTorque": "Trms = √[(T1²t1 + T2²t2 + T3²t3)/(t1 + t2 + t3)]",
  "screwCriticalSpeed": "ncrit = Cs·4.76×10⁶·dr(in)/L(in)² · r = ndeclared/ncrit",
  "bearingAdjustedLife": "L10 = (C/P)^p · Ladj = L10·a1·a2·a3 · hours = Ladj·10^6/(60n)",
  "boltLoad": "σ = Ft/(πd²/4) · τ = Fs/(πd²/4) · σbearing = Fb/(dt)",
  "cantileverFrame": "Vbase = H · Mbase = Hh",
  "stability": "Pcr = π²EI / (KL)²",
  "toolDeflection": "I = πd⁴/64 · δ = FL³/(3EI) · σ = 32FL/(πd³)",
  "torsion": "J = πD⁴/32 · τmax = Tc/J · φ = TL/GJ · P = Tω",
  "triangleTruss": "ΣFy = 0 · RA = RB = P/2 · Ndiagonal = (P/2)/sin θ · Nbottom = Ndiagonal cos θ",
  "vesselGeometry": "Vi = π(Di/2)²L · Ai = πDiL · Vshell = π[(Di/2+t)² − (Di/2)²]L",
  "shaftCombined": "σb = 32M/(πd³) · τt = 16T/(πd³) · σvm = √(σb² + 3τt²)",
  "idealGas": "pV = nRuT · ρ = pM/(RuT) = p/(RspecT)",
  "hydraulicReservoirDwell": "tdwell = Vworking/Qreturn · Vref = Qreturn·tref · ratio = tdwell/tref",
  "idealGasEntropyChange": "Δs = cp·ln(T₂/T₁) − R·ln(p₂/p₁)",
  "manningUniformFlow": "v = (1/n)·R^(2/3)·S^(1/2) · Q = A·v (metric uniform-flow form)",
  "npshAvailableBudget": "NPSHa = Hsurface + Hsuction − Hloss − Hvapor · stated difference = NPSHa − NPSHr",
  "robotPayloadMoment": "Fg = m·g · Mstatic = Fg·e",
  "robotReach": "r = √(x² + y² + z²) · rratio = r/Rref",
  "reflectedInertia": "Jref = JL / N² · Jtotal = JM + Jref",
  "convectionHeat": "Q̇ = hAΔT",
  "wristInertia": "Iaxis = Icg + mr² · Itotal = IEOAT,axis + Ipayload,axis",
  "couplingTorsion": "θ = T/kt · U = T²/(2kt)",
  "fractureIntensity": "KI = Yσ√(πa) · ratio = KI / KIC,declared",
  "jointSeparation": "C = kb/(kb+km) · ΔFb = CP · Fm = Fp−(1−C)P · Psep = Fp/(1−C)",
  "rotaryIndexing": "θ = α·π/180 · ωavg = θ/tmove · rate(move-only) = 60/tmove · KE = ½Iωavg²",
  "motionDuty": "α = (ω1−ω0)/tacc · Tacc = Jα · Trms = √(ΣTᵢ²tᵢ/Σtᵢ) · Ereleased = ½J(ω0²−ω1²)",
  "gravitationalPe": "PE = m g h",
  "pipeVelocity": "V = 4 Q / (π D²)",
  "dynamicPressure": "q = ½ ρ V²",
  "boltPreload": "P = T / (K·D) · uncertainty band = P(1 ± u)",
  "thinVessel": "σhoop = pD/(2t) · σlong = pD/(4t), closed thin cylinder",
  "keyway": "Ft = 2T/D · τkey = Ft/(wL) · σbearing = Ft/[(h/2)L]",
  "goodmanFatigue": "σa = Kfσa,nom · σm = Kfσm,nom · U = σa/Sn + σm/Su",
  "gearRatio": "i = z₂/z₁ · n₂ = n₁/i · T₂ = T₁iη",
  "wormDrive": "i = Zw/S · nout = nin/i · Tout = Tin iη",
  "beltTension": "ΔF = T/rp · Ftight = ΔF + Floose,declared",
  "frictionClutch": "Tfriction = z·μ·Fa·rm · ratio = Tfriction / Tdeclared",
  "cuttingPower": "Pc = ap f vc Kc /(60 × 10³) · Pmachine = Pc/η",
  "drillPointDepth": "hpoint = (D/2)/tan(θ/2) · hprogram = hfull + hpoint",
  "fixtureClamping": "Fdesign = Fcut M · Nrequired = Fdesign/μ · Ffriction = μN",
  "pickPlaceCycle": "tcycle = tout + tback + tpick + tplace + taux · throughput = 3600/tcycle · tbatch = Ntcycle",
  "payloadInertia": "mpayload = me + mp · first moment = mpayload r · Ipoint = mpayload r²",
  "reynoldsNumber": "Re = ρuDh/μ = uDh/ν · ν = μ/ρ · ratio = Re/Reref",
  "buoyancyForce": "FB = ρf·g·Vd · W = m·g · Fnet = FB − W",
  "flywheelEnergy": "ω = 2πn/60 · E = ½Iω² · ΔE = E2 − E1",
  "hertzContact": "1/E* = (1−ν₁²)/E₁ + (1−ν₂²)/E₂ · a = [3FR/(4E*)]^(1/3) · p₀ = 3F/(2πa²)",
  "deflectionCheck": "δreference = L / nreference · ratio = δdeclared / δreference",
  "plateBuckling": "σcr = kπ²E/[12(1−ν²)](t/b)²",
  "ballScrewLife": "L10 = (Ca/Fa)³·10⁶ rev · s = L10·Ph · telapsed = L10/[60n·ftravel]",
  "driveTrain": "rtotal = r1r2r3 · ηtotal = η1η2η3 · n2 = n1/rtotal · T2 = T1rtotalηtotal",
  "gripperHold": "Fgrip = m(g + a)·S/μ · Fj = Fgrip/z",
  "pneumaticDemandBudget": "nactive = ncycle·z·D/100 · Qavg = qcycle·nactive · ratio = Qavg/Qref",
  "hydraulicLossBudget": "Ploss = Δp·Q/600 · Pavg = Ploss·D/100 · Eper elapsed hour = Pavg·1 h",
  "vacuumLeakageBudget": "Qleak,avg = qleak·z·D/100 · ratio = Qleak,avg/Qref · Vper elapsed hour = 60·Qleak,avg",
  "hydraulicAccumulatorState": "P₀·V₀ⁿ = P·Vⁿ · V(P) = V₀·(P₀/P)^(1/n) · ΔVfluid = V(Pmin) − V(Pmax)",
  "pumpSystemHeadPoint": "Hsystem(Q) = Hstatic + K·Q²",
  "thermalRcStep": "τ = R·C · ΔT(t) = P·R·(1 − e^(−t/τ)) · Tnode = Tamb + ΔT(t)",
  "compressibleMassFlow": "ṁ = (A·pt/√Tt)·√(γ/R)·M·[1 + ((γ − 1)/2)·M²]^(−(γ + 1)/(2(γ − 1)))",
  "machiningTimeBudget": "tcut = Lcut / Ffeed · ttotal = tcut + tallowance",
  "threePhasePower": "S = √3·VLL·I · P = S·PF",
  "sheetBendAllowance": "BA = θ·(π/180)·(R + K·T) · BD = 2·(R + T)·tan(θ/2) − BA",
  "splineLoad": "Ft = 2T/Dp · zeffective = z·ηshare · Ftooth = Ft/zeffective · pnominal = Ftooth/(Le·he)",
  "gearMeshForce": "Ft = 2T/dp · Fr = Ft·tan(αt) · Fa = Ft·tan(β) · FN = √(Ft² + Fr² + Fa²)",
  "threadTensileArea": "At = 0.7854(D − 0.938194P)²",
  "toleranceStack": "TWC = Σ|tᵢ| · TRSS = √(Σtᵢ²), up to six visible contributors",
  "weldGroup": "Ltotal = 2L · Ju = Lb²/2 + L³/6 · qdirect = F/Ltotal · qtorsion,end = M·rmax/Ju",
  "threadDesign": "Dtap = Dmajor − P·E · Ats = πnLeDsmin[1/(2n)+0.57735(Dsmin−Enmax)] · Fscreen = Atsτallow",
  "orificeFlow": "Q = CdA2√[2(p1−p2)/(ρ(1−β⁴))] · ṁ = ρQ · β = D2/D1",
  "fatigueConcentration": "Kf = 1 + q(Kt − 1) · σeffective = Kfσnom",
  "planetaryGear": "i = 1 + Nr/Ns · Np = (Nr − Ns)/2 · ncarrier = nsun/i · Tcarrier = Tsun iη",
  "torqueSpeedDuty": "α = Δn(2π/60)/ta · Tacc = Jα · Treq = Tload + Tacc · P = Treqω",
  "pneumaticCycleTime": "Ahead = πD²/4 · Aannulus = π(D² − d²)/4 · v = Qactual/A · t = L/v",
  "additiveBuild": "mpart = Vρ · msupport = mpart s · teffective = V(1+s)/R · Cdirect = (mpart + msupport)cm + teffective ch + C0",
  "gravityMoment": "W = mg · r⊥ = r sin θ · Mg = mgr sin θ · Mresidual = Mc − Mg",
  "pitchCircle": "r = PCD/2 · Δθ = 360°/n · chord = 2r sin(π/n) · xi = r cos(θ₀+iΔθ) · yi = r sin(θ₀+iΔθ)",
  "regularPolygon": "P = ns · a = s/[2 tan(π/n)] · R = s/[2 sin(π/n)] · α = (n−2)180°/n · A = aP/2",
  "eccentricBoltGroup": "M = Fe · Vdirect = F/n · Σr² = nr² · Vtorsion = Mr/Σr² = M/(nr) · Vconservative = Vdirect + Vtorsion · τnom = Vconservative/(πd²/4)",
  "vacuumEvacuation": "t = (V/S) ln(p₁/p₂) · Srequired = (V/ttarget) ln(p₁/p₂)",
  "toggleForce": "MA = 1/[2 tan(θ)] · Fout = Fin · MA",
  "pneumaticLineLoss": "A = πD²/4 · v = Q/A · Δp = f(L/D)(ρv²/2) · guard: Δp/p₁ < 10%",
  "tappingTorque": "T = k·d³·e · P = Tω = 2πTn/(60·1000)",
  "threadMachiningTime": "vf = p·n · tpass = L/vf · 60 · ttotal = N(tpass + tr)",
  "minorLosses": "Δpminor = ΣK·ρv²/2 · hminor = Δp/(ρg)",
  "submergedPlane": "F = ρgycA · Ix = bh³/12 · yCP = yc + Ix/(Ayc)",
  "thermalResistance": "Rtotal = 1/(hhAh) + L/(kAw) + Rc + 1/(hcAc) · ΔT = Q̇Rtotal",
  "ballScrewSizing": "v = Pn/60000 · T = FaP/(2πη) · Pmech = Tω",
  "rackPinion": "Fr = mgμ + ma + Fe · Tp = Frdp/2 · np = 60v/(πdp) · P = Frv",
  "beltAxis": "Fa = mgμ · np = 60v/(πdp) · T = Fadp/(2η) · P = Fav",
  "hydraulicCylinder": "Ap = πD²/4 · Aa = Ap−πd²/4 · F = pA · V = As · v = Q/A · t = s/v",
  "hydraulicPump": "Qideal = Vd·n · Qdeclared = ηvQideal · Phyd = ΔpQ/600 · Pin = Phyd/ηo · Ttheory = ΔpVd/(2π)",
  "hydraulicMotor": "Ttheory = ΔpVd/(2π) · Tdeclared = ηmTtheory · nideal = Q/Vd · ndeclar​ed = ηvnideal · Pshaft = Tω",
  "hydraulicLine": "A = πDi²/4 · vmean = Q/A · Δpmajor = f(L/Di)(ρv²/2) · comparison = vmean/vref",
  "pressFit": "δ = Ds−Di · p = (δ/Di)E[(Do²−Di²)/(Do²+Di²)] · Fμ = πDiLpμ · Tμ = FμDi/2",
  "sheetMetalBend": "BA = (π/180)B(IR + K·MT) · OSSB = tan(B/2)(IR + MT) · BD = 2OSSB − BA · Flat = L₁ + L₂ − BD",
  "productionMetrics": "Run = PPT−ST · A = Run/PPT · P = ICT·N/Run · Q = G/N · OEE = A·P·Q · takt = PPT/D",
  "gageRr": "Crossed ANOVA: SSPart, SSOperator, SSPart×Operator, SSRepeatability · VarRepeat = MSRepeat · VarOperator = max[(MSOperator−MSInteraction)/(a·n),0]",
  "measurementUncertainty": "uc = √(uA² + uCal² + uRes² + uEnv²) · U = k·uc",
  "thermalRadiation": "qnet = εσA(Ts⁴ − Tsur⁴) · q''net = εσ(Ts⁴ − Tsur⁴)",
  "shaftDesign": "dmin = ∛(16T/πτallow) · τ = 16T/(πd³) · θ = TL/(GJ) · δcenter = FL³/(48EI) · ω₁ = (π²/L²)√(EI/m′)",
  "bearingLoad": "P = XFr + YFa · Creq = P·L10^(1/p) · static ratio = C0/P0 · DN = d·n",
  "filletWeld": "t = 0.707a · Aeff = 0.707aLn · τ = F/Aeff · amin = F/(0.707Lτallow n) · HI = VI·60·η/(1000v)",
  "triangle": "c = √(a² + b²) · A = ab / 2 · α = tan⁻¹(b/a)",
  "mohrCircle": "σavg = (σx + σy)/2 · R = √[((σx−σy)/2)² + τxy²] · σ1,2 = σavg ± R · 2θp = atan2(2τxy, σx−σy) · 2θs = 2θp + 90°",
  "motionProfile": "a = s / [ta(ta + tc)] · vmax = a·ta · T = 2ta + tc",
  "pneumatic": "Fextend = P·Abore·η · Fretract = P(Abore − Arod)·η",
  "clampForce": "Ftransfer = F·sin(θ)·η · Fpivot = F·|cos(θ)|",
  "leadScrew": "T = F·l/(2πη) · v = l·n/60 · P = Fv",
  "airConsumption": "Vfree = (Aextend + Aretract)s·(Pgauge + 1 bar)",
  "circularArc": "s = rθ · c = 2r sin(θ/2) · Asector = r²θ/2 · Asegment = Asector − r²sinθ/2",
  "compressionSpring": "k = Gd⁴/(8D³Na) · F = kδ · τbasic = 8FD/(πd³)",
  "drillingTime": "vc = πDcn/1000 · vf = frn · Tc = ld·i/(frn)",
  "processCapability": "Cp = (USL−LSL)/(6s) · Cpk = min[(USL−x̄)/(3s), (x̄−LSL)/(3s)]",
  "torsionSpring": "k_360 = E·d⁴/(10.8·D·n) · kθ = k_360/360 · M = kθ·θ · σnom = 32M/(πd³)",
  "cuttingParameters": "n = 1000vc/(πDc) · vf = fz·z·n · MRR = ap·ae·vf/1000 · Pc = ap·ae·vf·Kc/(60·10⁶·η)",
  "pinStress": "Fpin = F/n · As = πd²/4 · τnom = Fpin/(pAs) · Aprojected = dt · σbearing = Fpin/(dt)",
  "dimensionCheck": "Compare entered exponent vectors over SI base dimensions: [M, L, T, I, Θ, N, J]left − [M, L, T, I, Θ, N, J]right",
  "sCurveProfile": "tacc = v/aavg · vpeak = min(vmax, √(d aavg)) · ttotal = 2tacc + tcruise · apeak = aavg/(1 − 0.005J%)",
  "formControl": "Observed screening span = user-entered xmax − user-entered xmin",
  "orientationControl": "observed variation = rmax − rmin · ratio = observed variation / stated tolerance",
  "profileRunout": "observed variation = rmax − rmin · ratio = observed variation / stated tolerance",
  "beam": "δmax = PL³ / 3EI · Mmax = PL",
  "linearGuideLife": "L10 = Lref(C/Pc)^p · thours = L10·1000/(v·60)",
  "brakingDuty": "PW = MW·BT · R = Vdc²/PW · DC = tb/tc · DBRW = PW·DC·(1/2 normal, 1 overhauling)",
  "motorOperatingPoint": "Pshaft = T·ω = T·n·2π/60 · rT = T/Tref · rP = Pshaft/Pref",
  "conveyorLine": "q = v·1000/p",
  "darcyFrictionFactor": "fD = 0.25 / [log10(ε/(3.7D) + 5.74/Re^0.9)]²",
  "taylorToolLife": "V·Tⁿ = C · T = (C/V)^(1/n)",
  "mmc": "Bonus = actual hole − MMC hole · VC = MMC hole − ⌀T",
  "bearingLife": "L10 = (C/P)³ · hours = L10·10⁶/(60n)",
  "lmtd": "ΔTlm = (ΔT1 − ΔT2) / ln(ΔT1/ΔT2) · Q = UAΔTlm, counterflow",
  "driveRatio": "i = N2/N1 · n2 = n1/i · T2 = T1·i·η · v = πd1n1/60 · Ft = 2T1/d1",
  "vacuumHolding": "FTH = m(g + a)M",
  "gearToothStress": "σF = Ft/(b m Y)",
  "isentropicMachine": "T2s/T1 = (p2/p1)^((γ−1)/γ) · wis = cp(T2s−T1) · wactual = wis/ηis · P = ṁw",
};
