import type { InstrumentDocument } from "@/lib/document";

/** 16-pilot closed-form algebra. Shop numbers stay on the glass; expressions match the previous TypeScript. */
export const pilotDocuments: Record<string, InstrumentDocument> = {
  boltPreload: {
    slug: "boltPreload",
    title: "Torque–preload screen",
    description: "Estimate a nominal preload from applied torque, nominal diameter, and a user-entered torque coefficient with uncertainty made explicit.",
    domain: "mechanics",
    fields: [
      { id: "torque", label: "Applied torque", symbol: "T", help: "Applied tightening torque for the one stated fastener.", defaultValue: 80, defaultUnit: "N·m" },
      { id: "diameter", label: "Nominal diameter", symbol: "D", help: "Nominal bolt shank diameter used in the nut-factor relationship.", defaultValue: 12, defaultUnit: "mm" },
      { id: "nutFactor", label: "Torque coefficient", symbol: "K", help: "User-entered nut factor; friction and lubrication strongly affect it.", defaultValue: 0.2, defaultUnit: "—" },
      { id: "uncertainty", label: "Preload uncertainty", symbol: "±u", help: "User-entered one-sided uncertainty magnitude from 0 to 100.", defaultValue: 25, defaultUnit: "%" },
    ],
    outputs: [
      { id: "preload", label: "Nominal preload", defaultUnit: "kN", expression: "torque/(nutFactor*diameter)" },
      { id: "lower", label: "Estimated lower preload", defaultUnit: "kN", expression: "torque/(nutFactor*diameter)*(1-uncertainty/100)" },
      { id: "upper", label: "Estimated upper preload", defaultUnit: "kN", expression: "torque/(nutFactor*diameter)*(1+uncertainty/100)" },
    ],
    formula: "P = T / (K·D) · uncertainty band = P(1 ± u)",
    purpose: "Estimate a nominal preload from applied torque, nominal diameter, and a user-entered torque coefficient with uncertainty made explicit.",
    assumptions: ["One preloaded fastener", "User-entered nut factor", "Nominal diameter approximation"],
    boundary: "Not a design stamp. Use only inside the stated model boundary.",
    interpretation: "Nominal preload · uncertainty band",
    sourceLabel: "NASA preloaded-joint reference",
    sourceUrl: "https://engineeringlibrary.org/reference/preloaded-bolted-joint-analysis-methodology-nasa",
    related: [],
    warnings: ["Torque is an indirect and friction-sensitive way to create preload. This screen does not determine allowable preload, bolt proof/yield, thread strength, joint stiffness, separation, fatigue, thermal effects, relaxation, lubrication procedure, or a safe tightening specification."],
  },
  thinVessel: {
    slug: "thinVessel",
    title: "Thin-wall vessel stress",
    description: "Calculate ideal hoop and longitudinal membrane stresses for a closed, thin-walled cylindrical pressure vessel from user-entered pressure and nominal geometry.",
    domain: "mechanics",
    fields: [
      { id: "pressure", label: "Internal gauge pressure", symbol: "p", help: "Uniform internal gauge pressure; enter a positive magnitude.", defaultValue: 1.2, defaultUnit: "MPa" },
      { id: "diameter", label: "Inside diameter", symbol: "D", help: "Nominal inside diameter of the closed cylindrical shell.", defaultValue: 600, defaultUnit: "mm" },
      { id: "thickness", label: "Wall thickness", symbol: "t", help: "Uniform shell wall thickness for the thin-wall screen.", defaultValue: 12, defaultUnit: "mm" },
    ],
    outputs: [
      { id: "hoop", label: "Ideal hoop membrane stress", defaultUnit: "MPa", expression: "pressure*diameter/(2*thickness)" },
      { id: "longitudinal", label: "Ideal longitudinal membrane stress", defaultUnit: "MPa", expression: "pressure*diameter/(4*thickness)" },
      { id: "diameterThickness", label: "Inside diameter-to-thickness ratio", defaultUnit: "—", expression: "diameter/thickness" },
    ],
    formula: "σhoop = pD/(2t) · σlong = pD/(4t), closed thin cylinder",
    purpose: "Calculate ideal hoop and longitudinal membrane stresses for a closed, thin-walled cylindrical pressure vessel from user-entered pressure and nominal geometry.",
    assumptions: ["Closed cylindrical shell", "Thin wall", "Uniform internal pressure", "Membrane stress only"],
    boundary: "Not a design stamp. Use only inside the stated model boundary.",
    interpretation: "Hoop stress · longitudinal stress · D/t",
    sourceLabel: "Boston University thin-wall vessel reference",
    sourceUrl: "https://www.bu.edu/moss/mechanics-of-materials-combined-loading/",
    related: [],
    warnings: ["This is a closed cylindrical thin-shell membrane-stress relationship. It excludes thick-wall behavior, discontinuities, heads, nozzles, welds, external pressure, fatigue, corrosion allowance, material allowables, code requirements, relief sizing, and pressure-vessel certification."],
  },
  keyway: {
    slug: "keyway",
    title: "Parallel key / keyway stress",
    description: "Calculate tangential force and nominal parallel-key shear and bearing stress from user-entered shaft, key, and torque geometry.",
    domain: "mechanics",
    fields: [
      { id: "shaftDiameter", label: "Shaft diameter", symbol: "D", help: "Nominal shaft diameter at the key engagement.", defaultValue: 40, defaultUnit: "mm" },
      { id: "torque", label: "Transferred torque", symbol: "T", help: "Known steady torque applied to the single keyed connection.", defaultValue: 200, defaultUnit: "N·m" },
      { id: "width", label: "Key width", symbol: "w", help: "Nominal rectangular key width at the shear plane.", defaultValue: 12, defaultUnit: "mm" },
      { id: "height", label: "Key height", symbol: "h", help: "Nominal rectangular key height; half height is used in the simplified bearing area.", defaultValue: 8, defaultUnit: "mm" },
      { id: "length", label: "Engagement length", symbol: "L", help: "Fully engaged key length under the stated direct-load model.", defaultValue: 50, defaultUnit: "mm" },
    ],
    outputs: [
      { id: "tangentialForce", label: "Shaft tangential force", defaultUnit: "N", expression: "2*torque/(shaftDiameter/1000)" },
      { id: "shearStress", label: "Nominal key shear stress", defaultUnit: "MPa", expression: "2*torque*1000/(shaftDiameter*width*length)" },
      { id: "bearingStress", label: "Nominal key bearing stress", defaultUnit: "MPa", expression: "4000*torque/(shaftDiameter*height*length)" },
    ],
    formula: "Ft = 2T/D · τkey = Ft/(wL) · σbearing = Ft/[(h/2)L]",
    purpose: "Calculate tangential force and nominal parallel-key shear and bearing stress from user-entered shaft, key, and torque geometry.",
    assumptions: ["Single rectangular key", "Known steady torque", "Full stated engagement", "Nominal direct stress"],
    boundary: "Not a design stamp. Use only inside the stated model boundary.",
    interpretation: "Tangential force · key shear · bearing stress",
    sourceLabel: "FIRGELLI keyway engineering reference",
    sourceUrl: "https://www.firgelliauto.com/blogs/engineering-calculators/keyway-and-key-size-calculator",
    related: [],
    warnings: ["This is a single rectangular-key, steady-torque direct-stress screen. It excludes key/keyway standards selection, root stress concentration, shaft weakening, fit clearance, hub deformation, multiple keys, load sharing, assembly, fatigue, material allowables, lubrication, transients, and design approval."],
  },
  goodmanFatigue: {
    slug: "goodmanFatigue",
    title: "Goodman fatigue screen",
    description: "Calculate Kf-adjusted stresses and a linear Goodman utilization from declared nominal stresses and fatigue strengths.",
    domain: "mechanics",
    fields: [
      { id: "nominalAlternating", label: "Declared nominal alternating stress", symbol: "σa,nom", help: "User-entered high-cycle alternating stress before the declared Kf multiplier.", defaultValue: 80, defaultUnit: "MPa", signed: true },
      { id: "nominalMean", label: "Declared nominal mean stress", symbol: "σm,nom", help: "User-entered mean stress before the declared Kf multiplier.", defaultValue: 60, defaultUnit: "MPa", signed: true },
      { id: "kf", label: "Declared fatigue stress concentration", symbol: "Kf", help: "User-entered fatigue concentration factor; no geometry or material inference is made.", defaultValue: 1.6, defaultUnit: "—" },
      { id: "enduranceLimit", label: "Declared endurance limit", symbol: "Sn", help: "User-entered corrected endurance limit for the specific stated condition.", defaultValue: 180, defaultUnit: "MPa" },
      { id: "ultimateStrength", label: "Declared ultimate strength", symbol: "Su", help: "User-entered ultimate tensile strength used in the Goodman denominator.", defaultValue: 600, defaultUnit: "MPa" },
    ],
    outputs: [
      { id: "adjustedAlternating", label: "Kf-adjusted alternating stress", defaultUnit: "MPa", expression: "kf*nominalAlternating" },
      { id: "adjustedMean", label: "Kf-adjusted mean stress", defaultUnit: "MPa", expression: "kf*nominalMean" },
      { id: "utilization", label: "Linear Goodman utilization", defaultUnit: "—", expression: "kf*nominalAlternating/enduranceLimit+kf*nominalMean/ultimateStrength" },
    ],
    formula: "σa = Kfσa,nom · σm = Kfσm,nom · U = σa/Sn + σm/Su",
    purpose: "Calculate Kf-adjusted stresses and a linear Goodman utilization from declared nominal stresses and fatigue strengths.",
    assumptions: ["High-cycle stress life", "User-entered fatigue strengths", "User-entered Kf", "Linear Goodman relation"],
    boundary: "Not a design stamp. Use only inside the stated model boundary.",
    interpretation: "Adjusted stress · utilization",
    sourceLabel: "University of Illinois MechRef fatigue theory",
    sourceUrl: "https://www.mechref.org/mf/Fatigue/?origin=coursemenu",
    related: [],
    warnings: ["This high-cycle linear Goodman screen does not establish a pass/fail criterion or model endurance modifiers, yield, low-cycle fatigue, multiaxial loading, reliability, life, or design approval."],
  },
  gearRatio: {
    slug: "gearRatio",
    title: "Ideal gear ratio",
    description: "Resolve ideal output speed and efficiency-adjusted output torque from a driver and driven tooth count with a user-entered transmission efficiency.",
    domain: "mechanics",
    fields: [
      { id: "driverTeeth", label: "Driver teeth", symbol: "z₁", help: "Tooth count of the input gear in one external gear pair.", defaultValue: 20, defaultUnit: "teeth" },
      { id: "drivenTeeth", label: "Driven teeth", symbol: "z₂", help: "Tooth count of the output gear in the same pair.", defaultValue: 60, defaultUnit: "teeth" },
      { id: "inputRpm", label: "Input speed", symbol: "n₁", help: "Constant driver rotational speed.", defaultValue: 1800, defaultUnit: "rpm" },
      { id: "inputTorque", label: "Input torque", symbol: "T₁", help: "Steady driver torque.", defaultValue: 18, defaultUnit: "N·m" },
      { id: "efficiency", label: "Transmission efficiency", symbol: "η", help: "User-entered efficiency from 0 to 100.", defaultValue: 92, defaultUnit: "%" },
    ],
    outputs: [
      { id: "ratio", label: "Speed reduction ratio", defaultUnit: ":1", expression: "drivenTeeth/driverTeeth" },
      { id: "outputRpm", label: "Ideal output speed", defaultUnit: "rpm", expression: "inputRpm/(drivenTeeth/driverTeeth)" },
      { id: "outputTorque", label: "Efficiency-adjusted output torque", defaultUnit: "N·m", expression: "inputTorque*(drivenTeeth/driverTeeth)*(efficiency/100)" },
      { id: "inputPower", label: "Input mechanical power", defaultUnit: "kW", expression: "inputTorque*(2*pi*inputRpm/60)/1000" },
    ],
    formula: "i = z₂/z₁ · n₂ = n₁/i · T₂ = T₁iη",
    purpose: "Resolve ideal output speed and efficiency-adjusted output torque from a driver and driven tooth count with a user-entered transmission efficiency.",
    assumptions: ["One ideal external gear pair", "User-entered efficiency", "Constant input speed and torque", "No gear strength check"],
    boundary: "Not a design stamp. Use only inside the stated model boundary.",
    interpretation: "Reduction ratio · output speed · output torque",
    sourceLabel: "Motion-control gear-ratio context",
    sourceUrl: "https://www.motioncontroltips.com/how-do-gearmotors-impact-reflected-mass-inertia-from-the-load/",
    related: [],
    warnings: ["This screen covers one ideal external gear pair with a user-entered efficiency. It excludes tooth geometry, mesh force, strength, backlash, lubrication, shaft/bearing load, thermal behavior, vibration, noise, duty cycle, and gearbox or component selection."],
  },
  wormDrive: {
    slug: "wormDrive",
    title: "Worm-drive ratio",
    description: "Calculate ideal worm ratio, output speed, and declared-efficiency torque from wheel teeth, worm starts, speed, and torque.",
    domain: "mechanics",
    fields: [
      { id: "wheelTeeth", label: "Worm-wheel teeth", symbol: "Zw", help: "Declared driven wheel tooth count for the ideal worm reduction.", defaultValue: 50, defaultUnit: "teeth" },
      { id: "wormStarts", label: "Worm starts", symbol: "S", help: "Declared worm thread starts; it is the ideal driving tooth count.", defaultValue: 1, defaultUnit: "starts" },
      { id: "inputSpeed", label: "Worm input speed", symbol: "nin", help: "Declared worm input speed for the ideal speed reduction.", defaultValue: 1400, defaultUnit: "rpm" },
      { id: "inputTorque", label: "Worm input torque", symbol: "Tin", help: "Declared worm input torque before user-entered efficiency.", defaultValue: 5, defaultUnit: "N·m" },
      { id: "efficiency", label: "Declared worm-drive efficiency", symbol: "η", help: "User-entered drive efficiency; this workspace does not predict it.", defaultValue: 70, defaultUnit: "%" },
    ],
    outputs: [
      { id: "ratio", label: "Ideal worm reduction ratio", defaultUnit: ":1", expression: "wheelTeeth/wormStarts" },
      { id: "outputSpeed", label: "Ideal wheel output speed", defaultUnit: "rpm", expression: "inputSpeed/(wheelTeeth/wormStarts)" },
      { id: "outputTorque", label: "Declared-efficiency wheel torque", defaultUnit: "N·m", expression: "inputTorque*(wheelTeeth/wormStarts)*(efficiency/100)" },
    ],
    formula: "i = Zw/S · nout = nin/i · Tout = Tin iη",
    purpose: "Calculate ideal worm ratio, output speed, and declared-efficiency torque from wheel teeth, worm starts, speed, and torque.",
    assumptions: ["Ideal tooth ratio", "User-entered efficiency", "Steady speed", "Single reduction stage"],
    boundary: "Not a design stamp. Use only inside the stated model boundary.",
    interpretation: "Ratio · output speed · torque",
    sourceLabel: "Worm Gear Motors ratio guidance",
    sourceUrl: "https://wormgearmotorsonline.com/worm-gear-ratio-explained/",
    related: [],
    warnings: ["This is a one-stage ideal tooth-ratio screen with a user-entered efficiency. It does not select a worm set, predict efficiency or self-locking, model tooth contact/stress, heat, lubrication, backlash, noise, duty, durability, safety, or product suitability."],
  },
  beltTension: {
    slug: "beltTension",
    title: "Declared belt / chain tension",
    description: "Calculate the torque-induced tight/loose span tension difference and a stated tight-side sum from declared torque, pitch radius, and loose-side tension.",
    domain: "mechanics",
    fields: [
      { id: "driveTorque", label: "Declared drive torque", symbol: "T", help: "User-entered torque transmitted at the stated pulley/sprocket pitch radius.", defaultValue: 120, defaultUnit: "N·m" },
      { id: "pitchRadius", label: "Declared pitch radius", symbol: "rp", help: "User-entered driving pulley or sprocket pitch radius.", defaultValue: 75, defaultUnit: "mm" },
      { id: "looseSideTension", label: "Declared loose-side tension", symbol: "Floose", help: "User-entered stated loose-side tension used only for the literal tight-side sum.", defaultValue: 350, defaultUnit: "N", signed: true },
    ],
    outputs: [
      { id: "drivingTension", label: "Torque-induced driving tension difference", defaultUnit: "N", expression: "driveTorque*1000/pitchRadius" },
      { id: "declaredLooseSide", label: "Declared loose-side tension", defaultUnit: "N", expression: "looseSideTension" },
      { id: "tightSideTension", label: "Declared tight-side tension sum", defaultUnit: "N", expression: "driveTorque*1000/pitchRadius+looseSideTension" },
    ],
    formula: "ΔF = T/rp · Ftight = ΔF + Floose,declared",
    purpose: "Calculate the torque-induced tight/loose span tension difference and a stated tight-side sum from declared torque, pitch radius, and loose-side tension.",
    assumptions: ["Declared pitch radius", "Steady torque transmission", "User-entered loose-side tension", "Scalar belt/chain span relation"],
    boundary: "Not a design stamp. Use only inside the stated model boundary.",
    interpretation: "Driving tension · stated tight-side tension",
    sourceLabel: "EPI belt drive properties",
    sourceUrl: "https://www.epi-eng.com/propeller_reduction_technology/belt_drive_properties.htm",
    related: [],
    warnings: ["This is a torque-to-driving-tension difference and stated loose-side sum only. It excludes pretension selection, wrap, friction, slip, fatigue, speed capability, bearing loading, belt/chain selection, safety, and approval."],
  },
  frictionClutch: {
    slug: "frictionClutch",
    title: "Declared friction-interface torque",
    description: "Calculate stated friction-interface torque and its literal ratio to a user-entered torque demand from coefficient, clamp force, mean radius, and active surfaces.",
    domain: "mechanics",
    fields: [
      { id: "frictionCoefficient", label: "Declared friction coefficient", symbol: "μ", help: "User-entered interface coefficient for the stated condition; no material or condition is inferred.", defaultValue: 0.28, defaultUnit: "—" },
      { id: "clampForce", label: "Declared axial clamp force", symbol: "Fa", help: "User-entered normal clamp force on the stated friction interface.", defaultValue: 3200, defaultUnit: "N" },
      { id: "meanRadius", label: "Declared mean friction radius", symbol: "rm", help: "User-entered effective mean friction radius; pressure distribution is excluded.", defaultValue: 85, defaultUnit: "mm" },
      { id: "surfaceCount", label: "Declared active friction surfaces", symbol: "z", help: "Positive integer number of active friction surfaces in the stated model.", defaultValue: 2, defaultUnit: "surfaces" },
      { id: "torqueDemand", label: "Declared torque demand", symbol: "Td", help: "User-entered reference torque for literal ratio arithmetic only.", defaultValue: 120, defaultUnit: "N·m" },
    ],
    outputs: [
      { id: "frictionTorque", label: "Declared friction-interface torque", defaultUnit: "N·m", expression: "surfaceCount*frictionCoefficient*clampForce*(meanRadius/1000)" },
      { id: "demandRatio", label: "Friction torque / declared demand", defaultUnit: "—", expression: "surfaceCount*frictionCoefficient*clampForce*(meanRadius/1000)/torqueDemand" },
      { id: "arithmeticDifference", label: "Friction torque minus declared demand", defaultUnit: "N·m", expression: "surfaceCount*frictionCoefficient*clampForce*(meanRadius/1000)-torqueDemand" },
    ],
    formula: "Tfriction = z·μ·Fa·rm · ratio = Tfriction / Tdeclared",
    purpose: "Calculate stated friction-interface torque and its literal ratio to a user-entered torque demand from coefficient, clamp force, mean radius, and active surfaces.",
    assumptions: ["Uniform stated friction coefficient", "User-entered axial clamp force", "User-entered mean friction radius", "Declared active friction surfaces"],
    boundary: "Not a design stamp. Use only inside the stated model boundary.",
    interpretation: "Friction torque · demand ratio · arithmetic difference",
    sourceLabel: "x-engineer friction clutch torque relation",
    sourceUrl: "https://x-engineer.org/calculate-clutch-torque/",
    related: [],
    warnings: ["This is a stated uniform-friction torque relation for a user-defined clutch or brake interface. It excludes temperature, energy absorption, wear, pressure distribution, actuation, engagement dynamics, material selection, capacity, safety, and approval."],
  },
  cuttingPower: {
    slug: "cuttingPower",
    title: "Turning cutting power",
    description: "Calculate turning cutting power from declared depth, feed, speed, specific cutting force, and machine efficiency.",
    domain: "manufacturing",
    fields: [
      { id: "depth", label: "Depth of cut", symbol: "ap", help: "Declared radial turning depth of cut for the stated pass.", defaultValue: 3, defaultUnit: "mm" },
      { id: "feed", label: "Feed per revolution", symbol: "f", help: "Declared turning feed per revolution for the stated pass.", defaultValue: 0.2, defaultUnit: "mm/rev" },
      { id: "cuttingSpeed", label: "Cutting speed", symbol: "vc", help: "Declared cutting speed for the stated pass.", defaultValue: 120, defaultUnit: "m/min" },
      { id: "specificForce", label: "Declared specific cutting force", symbol: "Kc", help: "User-entered specific cutting force; no material or chip-thickness model is selected.", defaultValue: 3100, defaultUnit: "MPa" },
      { id: "efficiency", label: "Declared machine efficiency", symbol: "η", help: "User-entered machine coefficient used only in the direct power screen.", defaultValue: 80, defaultUnit: "%" },
    ],
    outputs: [
      { id: "cuttingPower", label: "Ideal cutting power", defaultUnit: "kW", expression: "depth*feed*cuttingSpeed*specificForce/60000" },
      { id: "machinePower", label: "Declared-efficiency machine input", defaultUnit: "kW", expression: "depth*feed*cuttingSpeed*specificForce/60000/(efficiency/100)" },
    ],
    formula: "Pc = ap f vc Kc /(60 × 10³) · Pmachine = Pc/η",
    purpose: "Calculate turning cutting power from declared depth, feed, speed, specific cutting force, and machine efficiency.",
    assumptions: ["Turning pass", "User-entered Kc", "Declared machine efficiency", "Steady cut"],
    boundary: "Not a design stamp. Use only inside the stated model boundary.",
    interpretation: "Uncorrected · machine-input power",
    sourceLabel: "Mitsubishi Materials turning cutting power",
    sourceUrl: "https://www.mmc-carbide.com/us/technical_information/formula/tec_turning_cutting_power_formula",
    related: [],
    warnings: ["Direct turning power screen only; parameter/tool selection, chip-thickness effects, chatter, thermal limits, wear, machine limits, safety, and production approval are excluded."],
  },
  drillPointDepth: {
    slug: "drillPointDepth",
    title: "Drill-point depth",
    description: "Calculate geometric drill-point depth and programmed depth for a declared full-diameter hole depth from drill diameter and included point angle.",
    domain: "manufacturing",
    fields: [
      { id: "diameter", label: "Drill diameter", symbol: "D", help: "Declared drill diameter used for exact conical point geometry.", defaultValue: 12, defaultUnit: "mm" },
      { id: "includedAngle", label: "Included point angle", symbol: "θ", help: "Declared full included conical point angle; it must be between 0 and 180 degrees.", defaultValue: 135, defaultUnit: "deg" },
      { id: "fullDiameterDepth", label: "Required full-diameter depth", symbol: "h", help: "Depth of the requested full-diameter cylindrical portion, excluding the drill point.", defaultValue: 25, defaultUnit: "mm" },
    ],
    outputs: [
      { id: "pointDepth", label: "Geometric drill-point depth", defaultUnit: "mm", expression: "diameter/2/tan((includedAngle/2)*pi/180)" },
      { id: "programmedDepth", label: "Programmed depth for declared full diameter", defaultUnit: "mm", expression: "fullDiameterDepth+diameter/2/tan((includedAngle/2)*pi/180)" },
    ],
    formula: "hpoint = (D/2)/tan(θ/2) · hprogram = hfull + hpoint",
    purpose: "Calculate geometric drill-point depth and programmed depth for a declared full-diameter hole depth from drill diameter and included point angle.",
    assumptions: ["Conical point", "Declared included angle", "Full-diameter depth", "No breakthrough allowance"],
    boundary: "Not a design stamp. Use only inside the stated model boundary.",
    interpretation: "Point depth · programmed depth",
    sourceLabel: "Haas drill-point depth guidance",
    sourceUrl: "https://www.haas.co.uk/resources/better-techniques/control-tips/working-out-drill-depth/",
    related: [],
    warnings: ["Ideal conical-point geometry only; drilling variation, wear, runout, breakthrough allowance, workholding, machine motion, cutting parameters, safety, and manufacturing approval are excluded."],
  },
  fixtureClamping: {
    slug: "fixtureClamping",
    title: "Fixture clamping force",
    description: "Calculate the normal clamping force required to resist a declared horizontal machining force through stated friction and force multiplier.",
    domain: "manufacturing",
    fields: [
      { id: "machiningForce", label: "Declared horizontal machining force", symbol: "Fcut", help: "User-entered horizontal machining force requiring frictional restraint.", defaultValue: 1800, defaultUnit: "N" },
      { id: "friction", label: "Declared clamp/workpiece friction", symbol: "μ", help: "User-entered static friction coefficient for this narrow horizontal-force screen.", defaultValue: 0.19, defaultUnit: "—" },
      { id: "serviceMultiplier", label: "Declared force multiplier", symbol: "M", help: "User-entered multiplier for the stated force context; it is not a prescribed safety factor.", defaultValue: 2, defaultUnit: "—" },
    ],
    outputs: [
      { id: "designHorizontalForce", label: "Multiplier-adjusted horizontal force", defaultUnit: "N", expression: "machiningForce*serviceMultiplier" },
      { id: "requiredNormalForce", label: "Friction-only required normal force", defaultUnit: "N", expression: "machiningForce*serviceMultiplier/friction" },
      { id: "frictionCapacity", label: "Friction capacity at required normal force", defaultUnit: "N", expression: "machiningForce*serviceMultiplier" },
    ],
    formula: "Fdesign = Fcut M · Nrequired = Fdesign/μ · Ffriction = μN",
    purpose: "Calculate the normal clamping force required to resist a declared horizontal machining force through stated friction and force multiplier.",
    assumptions: ["Horizontal cutting force", "Friction-only restraint", "Static screening", "Multiplier declared by user"],
    boundary: "Not a design stamp. Use only inside the stated model boundary.",
    interpretation: "Required normal force · friction capacity",
    sourceLabel: "Carr Lane clamping-force guide",
    sourceUrl: "https://www.carrlane.com/engineering-resources/fixture-design-principles/clamping-force-calculations",
    related: [],
    warnings: ["This is a friction-only horizontal-force screen. It does not analyze stops, lift, moments, clamp geometry, load distribution, workpiece deformation, vibration, dynamic loads, machine table stiffness, clamp capacity, fixture selection, or safety approval."],
  },
  pickPlaceCycle: {
    slug: "pickPlaceCycle",
    title: "Pick-and-place cycle",
    description: "Sum declared travel, dwell, and auxiliary times into a repeated pick-and-place cycle, throughput, and batch-duration screen.",
    domain: "manufacturing",
    fields: [
      { id: "outboundTime", label: "Outbound travel time", symbol: "tout", help: "User-entered travel time to the pick or place position.", defaultValue: 1.2, defaultUnit: "s", signed: true },
      { id: "inboundTime", label: "Return travel time", symbol: "tback", help: "User-entered return travel time for the same repeated cycle.", defaultValue: 1.1, defaultUnit: "s", signed: true },
      { id: "pickDwell", label: "Pick dwell", symbol: "tpick", help: "User-entered gripper or process dwell at pick.", defaultValue: 0.3, defaultUnit: "s", signed: true },
      { id: "placeDwell", label: "Place dwell", symbol: "tplace", help: "User-entered gripper or process dwell at place.", defaultValue: 0.3, defaultUnit: "s", signed: true },
      { id: "auxiliaryTime", label: "Auxiliary time", symbol: "taux", help: "User-entered transfer, sensing, or other time added to each cycle.", defaultValue: 0.2, defaultUnit: "s", signed: true },
      { id: "cycles", label: "Repeated cycles", symbol: "N", help: "Declared repeated cycle count for the batch-time result.", defaultValue: 100, defaultUnit: "cycles" },
    ],
    outputs: [
      { id: "cycleTime", label: "Declared repeated cycle time", defaultUnit: "s", expression: "outboundTime+inboundTime+pickDwell+placeDwell+auxiliaryTime" },
      { id: "hourlyThroughput", label: "Ideal hourly throughput", defaultUnit: "cycles/h", expression: "3600/(outboundTime+inboundTime+pickDwell+placeDwell+auxiliaryTime)" },
      { id: "batchTime", label: "Declared-cycle batch duration", defaultUnit: "min", expression: "(outboundTime+inboundTime+pickDwell+placeDwell+auxiliaryTime)*cycles/60" },
    ],
    formula: "tcycle = tout + tback + tpick + tplace + taux · throughput = 3600/tcycle · tbatch = Ntcycle",
    purpose: "Sum declared travel, dwell, and auxiliary times into a repeated pick-and-place cycle, throughput, and batch-duration screen.",
    assumptions: ["Repeated identical cycles", "Times entered by user", "No path simulation", "No overlap or queuing"],
    boundary: "Not a design stamp. Use only inside the stated model boundary.",
    interpretation: "Cycle time · hourly throughput · batch time",
    sourceLabel: "RoboDK robot cycle-time article",
    sourceUrl: "https://robodk.com/blog/robot-cycle-time/",
    related: [],
    warnings: ["This is a repeated timing sum from user-entered travel, dwell, and auxiliary times. It does not simulate robot paths, acceleration, blending, queuing, overlap, controller behavior, reach, collision, faults, payload limits, uptime, safety, or throughput guarantees."],
  },
  payloadInertia: {
    slug: "payloadInertia",
    title: "Payload inertia screen",
    description: "Calculate declared EOAT plus product payload and a point-mass inertia approximation from flange-to-CG distance.",
    domain: "mechanics",
    fields: [
      { id: "eoatMass", label: "EOAT mass", symbol: "me", help: "User-entered end-of-arm-tool mass.", defaultValue: 5, defaultUnit: "kg", signed: true },
      { id: "productMass", label: "Product mass", symbol: "mp", help: "User-entered handled product mass.", defaultValue: 2, defaultUnit: "kg", signed: true },
      { id: "cgDistance", label: "Flange-to-CG distance", symbol: "r", help: "User-entered center-of-gravity distance from the analyzed robot axis/flange.", defaultValue: 0.15, defaultUnit: "m", signed: true },
    ],
    outputs: [
      { id: "payloadMass", label: "Declared total payload mass", defaultUnit: "kg", expression: "eoatMass+productMass" },
      { id: "cgMoment", label: "Payload mass × CG distance", defaultUnit: "kg·m", expression: "(eoatMass+productMass)*cgDistance" },
      { id: "pointMassInertia", label: "Point-mass payload inertia", defaultUnit: "kg·m²", expression: "(eoatMass+productMass)*cgDistance^2" },
    ],
    formula: "mpayload = me + mp · first moment = mpayload r · Ipoint = mpayload r²",
    purpose: "Calculate declared EOAT plus product payload and a point-mass inertia approximation from flange-to-CG distance.",
    assumptions: ["Masses declared", "Single CG distance", "Point-mass inertia", "One analyzed axis"],
    boundary: "Not a design stamp. Use only inside the stated model boundary.",
    interpretation: "Payload mass · point-mass inertia · CG moment",
    sourceLabel: "Motion Controls Robotics payload-inertia explanation",
    sourceUrl: "https://motioncontrolsrobotics.com/resources/tech-talk-articles/robot-inertia-vs-payload/",
    related: [],
    warnings: ["This is a one-axis point-mass approximation using a single declared flange-to-CG distance. It does not calculate a full inertia tensor, model EOAT/product geometry, determine robot payload or axis limits, evaluate reach, motion, collision, capacity, safety, certification, or robot selection."],
  },
  reynoldsNumber: {
    slug: "reynoldsNumber",
    title: "Reynolds number",
    description: "Calculate Reynolds number from user-entered density, velocity, hydraulic diameter, and dynamic viscosity, with a contextual reference-ratio output.",
    domain: "fluids",
    fields: [
      { id: "density", label: "Declared fluid density", symbol: "ρ", help: "User-entered density at the stated condition; this workspace does not derive properties.", defaultValue: 1000, defaultUnit: "kg/m³" },
      { id: "velocity", label: "Declared bulk velocity", symbol: "u", help: "Representative velocity selected by the user for the stated passage.", defaultValue: 1.5, defaultUnit: "m/s", signed: true },
      { id: "hydraulicDiameter", label: "Declared hydraulic diameter", symbol: "Dh", help: "Characteristic hydraulic diameter for the stated passage; geometry is not derived.", defaultValue: 0.02, defaultUnit: "m" },
      { id: "dynamicViscosity", label: "Declared dynamic viscosity", symbol: "μ", help: "User-entered dynamic viscosity at the stated condition; temperature/property lookup is excluded.", defaultValue: 0.001, defaultUnit: "Pa·s" },
      { id: "referenceThreshold", label: "Declared reference threshold", symbol: "Reref", help: "Contextual divisor only; it does not classify flow or select a correlation.", defaultValue: 2300, defaultUnit: "—" },
    ],
    outputs: [
      { id: "reynolds", label: "Reynolds number", defaultUnit: "—", expression: "density*velocity*hydraulicDiameter/dynamicViscosity" },
      { id: "kinematicViscosity", label: "Declared-condition kinematic viscosity", defaultUnit: "m²/s", expression: "dynamicViscosity/density" },
      { id: "thresholdRatio", label: "Ratio to declared reference threshold", defaultUnit: "×", expression: "(density*velocity*hydraulicDiameter/dynamicViscosity)/referenceThreshold" },
    ],
    formula: "Re = ρuDh/μ = uDh/ν · ν = μ/ρ · ratio = Re/Reref",
    purpose: "Calculate Reynolds number from user-entered density, velocity, hydraulic diameter, and dynamic viscosity, with a contextual reference-ratio output.",
    assumptions: ["User-entered density and dynamic viscosity", "Declared bulk velocity", "Declared hydraulic diameter", "Reference threshold is contextual only"],
    boundary: "Not a design stamp. Use only inside the stated model boundary.",
    interpretation: "Reynolds number · kinematic viscosity · declared-threshold ratio",
    sourceLabel: "NASA Reynolds number reference",
    sourceUrl: "https://www.grc.nasa.gov/www/k-12/airplane/reynolds.html",
    related: [],
    warnings: ["This is a declared-property Reynolds-number arithmetic screen only. It does not classify a flow regime, select a friction factor or heat/mass-transfer correlation, calculate pressure loss, infer fluid properties, account for roughness, entrance effects, non-Newtonian behavior, multiphase flow, compressibility, geometry, equipment suitability, safety, or approval."],
  },
  buoyancyForce: {
    slug: "buoyancyForce",
    title: "Buoyancy force",
    description: "Calculate constant-density buoyant force, declared object weight, and their literal net-force difference.",
    domain: "fluids",
    fields: [
      { id: "fluidDensity", label: "Declared fluid density", symbol: "ρf", help: "Constant user-entered displaced-fluid density; stratification and property lookup are excluded.", defaultValue: 1000, defaultUnit: "kg/m³" },
      { id: "displacedVolume", label: "Declared displaced volume", symbol: "Vd", help: "User-entered displaced volume at the stated immersion condition; geometry is not inferred.", defaultValue: 12, defaultUnit: "L" },
      { id: "objectMass", label: "Declared object mass", symbol: "m", help: "User-entered mass used only for gravitational-weight comparison.", defaultValue: 10, defaultUnit: "kg", signed: true },
    ],
    outputs: [
      { id: "buoyancy", label: "Constant-density buoyant force", defaultUnit: "N", expression: "fluidDensity*9.80665*(displacedVolume/1000)" },
      { id: "weight", label: "Declared object gravitational weight", defaultUnit: "N", expression: "objectMass*9.80665" },
      { id: "netUpwardForce", label: "Buoyancy minus declared weight", defaultUnit: "N", expression: "fluidDensity*9.80665*(displacedVolume/1000)-objectMass*9.80665" },
      { id: "displacedMass", label: "Mass of declared displaced fluid", defaultUnit: "kg", expression: "fluidDensity*(displacedVolume/1000)" },
    ],
    formula: "FB = ρf·g·Vd · W = m·g · Fnet = FB − W",
    purpose: "Calculate constant-density buoyant force, declared object weight, and their literal net-force difference.",
    assumptions: ["Constant user-entered fluid density", "Declared displaced volume", "Declared object mass", "Standard gravitational acceleration"],
    boundary: "Not a design stamp. Use only inside the stated model boundary.",
    interpretation: "Buoyant force · weight · net upward force",
    sourceLabel: "Embry-Riddle fluid statics reference",
    sourceUrl: "https://eaglepubs.erau.edu/introductiontoaerospaceflightvehicles/chapter/fluid-statics/",
    related: [],
    warnings: ["This is constant-density displaced-volume force arithmetic only. It does not determine float or vessel stability, immersion equilibrium, free-surface effects, restoring moments, geometry, structural adequacy, material selection, pressure rating, installation conditions, safety, or approval."],
  },
  flywheelEnergy: {
    slug: "flywheelEnergy",
    title: "Flywheel energy change",
    description: "Calculate two rotational kinetic-energy states and their literal difference from user-entered inertia and initial/final speeds.",
    domain: "dynamics",
    fields: [
      { id: "inertia", label: "Declared rotational inertia", symbol: "I", help: "User-entered inertia about the stated rotation axis; geometry is not derived.", defaultValue: 0.8, defaultUnit: "kg·m²" },
      { id: "initialSpeed", label: "Declared initial speed", symbol: "n₁", help: "Initial non-negative speed magnitude for the stated rigid body.", defaultValue: 600, defaultUnit: "rpm", signed: true },
      { id: "finalSpeed", label: "Declared final speed", symbol: "n₂", help: "Final non-negative speed magnitude for the stated rigid body.", defaultValue: 1800, defaultUnit: "rpm", signed: true },
    ],
    outputs: [
      { id: "initialAngularSpeed", label: "Initial angular speed", defaultUnit: "rad/s", expression: "initialSpeed*2*pi/60" },
      { id: "finalAngularSpeed", label: "Final angular speed", defaultUnit: "rad/s", expression: "finalSpeed*2*pi/60" },
      { id: "initialEnergy", label: "Initial rotational kinetic energy", defaultUnit: "kJ", expression: "0.5*inertia*(initialSpeed*2*pi/60)^2/1000" },
      { id: "finalEnergy", label: "Final rotational kinetic energy", defaultUnit: "kJ", expression: "0.5*inertia*(finalSpeed*2*pi/60)^2/1000" },
      { id: "energyChange", label: "Final minus initial energy", defaultUnit: "kJ", expression: "(0.5*inertia*(finalSpeed*2*pi/60)^2-0.5*inertia*(initialSpeed*2*pi/60)^2)/1000" },
    ],
    formula: "ω = 2πn/60 · E = ½Iω² · ΔE = E2 − E1",
    purpose: "Calculate two rotational kinetic-energy states and their literal difference from user-entered inertia and initial/final speeds.",
    assumptions: ["Rigid declared inertia", "Steady initial and final speed states", "Classical rotational kinetic energy", "No loss model"],
    boundary: "Not a design stamp. Use only inside the stated model boundary.",
    interpretation: "Initial energy · final energy · energy change",
    sourceLabel: "Engineering ToolBox flywheel energy",
    sourceUrl: "https://www.engineeringtoolbox.com/flywheel-energy-d_945.html",
    related: [],
    warnings: ["This is a rigid-body two-state rotational kinetic-energy calculation. It excludes rotating-body stress, containment, balance, overspeed, acceleration torque, transient dynamics, losses, material selection, safety, and approval."],
  },
};
