/**
 * Engineering Desk — Instrument Panel Atelier reminder:
 * Diagrams are active configuration checks: simple, physical, and never decorative.
 */

import type { ToolId } from "@/lib/catalog";

export default function MechanicalDiagram({ toolId, variant }: { toolId: ToolId; variant?: string }) {
  if (toolId === "axial") {
    return <div className="mechanical-diagram axial-diagram" role="img" aria-label="Prismatic member with opposing axial loads"><span className="arrow left">← F</span><div className="axial-member" /><span className="arrow right">F →</span><span className="diagram-label">L</span></div>;
  }
  if (toolId === "beam") {
    const cantilever = variant === "cantilever";
    return <div className={`mechanical-diagram beam-diagram ${cantilever ? "beam-cantilever" : "beam-simple"}`} role="img" aria-label={cantilever ? "Cantilever beam with end point load" : "Simply supported beam with center point load"}><div className="beam-line" />{cantilever ? <><i className="wall" /><span className="load-arrow">P ↓</span></> : <><i className="support left" /><i className="support right" /><span className="load-arrow">P ↓</span></>}<span className="diagram-label">L</span></div>;
  }
  if (toolId === "beamDiagram") return <div className="mechanical-diagram converter-diagram" role="img" aria-label="Simply supported beam with point and uniformly distributed loading"><span>RA ↑ · RB ↑</span><i>←</i><b>P ↓ · w ↓</b><i>→</i><span>V(x) · M(x)</span></div>;
  if (toolId === "triangleTruss") return <div className="mechanical-diagram converter-diagram" role="img" aria-label="Symmetric triangular pin-jointed truss with vertical apex load"><span>RA · RB</span><i>→</i><b>P ↓</b><i>→</i><span>Ndiagonal · Nbottom</span></div>;
  if (toolId === "hertzContact") return <div className="mechanical-diagram converter-diagram" role="img" aria-label="Elastic sphere-on-flat Hertz contact relationship"><span>F · R · E*</span><i>→</i><b>a</b><i>→</i><span>p0 · δ</span></div>;
  if (toolId === "fractureIntensity") return <div className="mechanical-diagram converter-diagram" role="img" aria-label="Mode I linear elastic fracture stress intensity relation"><span>Y · σ · √πa</span><i>→</i><b>KI</b><i>÷</i><span>KIC declared</span></div>;
  if (toolId === "deflectionCheck") return <div className="mechanical-diagram converter-diagram" role="img" aria-label="Declared beam deflection compared to a stated span reference"><span>δdeclared</span><i>÷</i><b>L / nref</b><i>→</i><span>literal ratio</span></div>;
  if (toolId === "cantileverFrame") return <div className="mechanical-diagram converter-diagram" role="img" aria-label="Single vertical cantilever frame with declared lateral top load"><span>H at top</span><i>× h →</i><b>Vbase · Mbase</b><i>→</i><span>fixed base</span></div>;
  if (toolId === "plateBuckling") return <div className="mechanical-diagram converter-diagram" role="img" aria-label="Declared simply supported elastic plate buckling stress relation"><span>k · E · (t / b)²</span><i>÷</i><b>12(1 − ν²)</b><i>→</i><span>σcr</span></div>;
  if (toolId === "screwCriticalSpeed") return <div className="mechanical-diagram converter-diagram" role="img" aria-label="Declared screw critical speed relation"><span>Cs · dr</span><i>÷</i><b>L²</b><i>→</i><span>ncritical</span></div>;
  if (toolId === "linearGuideLife") return <div className="mechanical-diagram converter-diagram" role="img" aria-label="Declared linear guide dynamic rating life relation"><span>(C / P)ᵖ</span><i>×</i><b>reference travel</b><i>→</i><span>L10</span></div>;
  if (toolId === "brakingDuty") return <div className="mechanical-diagram converter-diagram" role="img" aria-label="Declared dynamic braking peak power and duty relation"><span>MW · BT</span><i>→</i><b>PW · DC</b><i>→</i><span>DBRW</span></div>;
  if (toolId === "ballScrewLife") return <div className="mechanical-diagram converter-diagram" role="img" aria-label="Declared ball screw axial rating life relation"><span>(Ca / Fa)³</span><i>×</i><b>10⁶ rev</b><i>→</i><span>travel · time</span></div>;
  if (toolId === "driveTrain") return <div className="mechanical-diagram converter-diagram" role="img" aria-label="Declared multi-stage drive train product relation"><span>r₁ · r₂ · r₃</span><i>×</i><b>η₁ · η₂ · η₃</b><i>→</i><span>n₂ · T₂</span></div>;
  if (toolId === "rmsDutyTorque") return <div className="mechanical-diagram converter-diagram" role="img" aria-label="Declared three segment RMS torque relation"><span>Σ(T² · t)</span><i>÷</i><b>Σt</b><i>→</i><span>Trms</span></div>;
  if (toolId === "motorOperatingPoint") return <div className="mechanical-diagram converter-diagram" role="img" aria-label="Declared motor torque speed shaft power relation"><span>T · n</span><i>×</i><b>2π / 60</b><i>→</i><span>Pshaft</span></div>;
  if (toolId === "gripperHold") return <div className="mechanical-diagram converter-diagram" role="img" aria-label="Declared parallel gripper friction hold relation"><span>m(g + a) · S</span><i>÷</i><b>μ</b><i>→</i><span>Fgrip</span></div>;
  if (toolId === "conveyorLine") return <div className="mechanical-diagram converter-diagram" role="img" aria-label="Declared conveyor speed and pitch rate relation"><span>v</span><i>÷</i><b>pitch</b><i>→</i><span>items/min</span></div>;
  if (toolId === "robotReach") return <div className="mechanical-diagram converter-diagram" role="img" aria-label="Declared robot radial target distance relation"><span>x² + y² + z²</span><i>√</i><b>reference reach</b><i>→</i><span>r / Rref</span></div>;
  if (toolId === "robotPayloadMoment") return <div className="mechanical-diagram converter-diagram" role="img" aria-label="Declared robot payload gravity moment relation"><span>m · g</span><i>×</i><b>CoG offset</b><i>→</i><span>Mstatic</span></div>;
  if (toolId === "rotaryIndexing") return <div className="mechanical-diagram converter-diagram" role="img" aria-label="Declared rotary indexing average-speed, rate, and energy relation"><span>θ / tmove</span><i>→</i><b>ωavg</b><i>→</i><span>KE · rate</span></div>;
  if (toolId === "pneumaticDemandBudget") return <div className="mechanical-diagram converter-diagram" role="img" aria-label="Declared pneumatic normalized air-demand budget relation"><span>NL/cycle · cycles/min</span><i>×</i><b>devices · duty</b><i>→</i><span>NL/min</span></div>;
  if (toolId === "hydraulicLossBudget") return <div className="mechanical-diagram converter-diagram" role="img" aria-label="Declared hydraulic pressure-drop power budget relation"><span>Δp · Q</span><i>÷</i><b>600</b><i>×</i><span>active fraction</span></div>;
  if (toolId === "vacuumLeakageBudget") return <div className="mechanical-diagram converter-diagram" role="img" aria-label="Declared vacuum leakage demand budget relation"><span>qleak · points</span><i>×</i><b>duty</b><i>→</i><span>Qleak / Qref</span></div>;
  if (toolId === "hydraulicAccumulatorState") return <div className="mechanical-diagram converter-diagram" role="img" aria-label="Declared hydraulic accumulator polytropic gas-state relation"><span>P₀ · V₀ⁿ</span><i>→</i><b>P · Vⁿ</b><i>→</i><span>ΔVfluid</span></div>;
  if (toolId === "hydraulicReservoirDwell") return <div className="mechanical-diagram converter-diagram" role="img" aria-label="Declared hydraulic reservoir dwell-time relation"><span>Vworking</span><i>÷</i><b>Qreturn</b><i>→</i><span>tdwell</span></div>;
  if (toolId === "darcyFrictionFactor") return <div className="mechanical-diagram converter-diagram" role="img" aria-label="Declared Darcy friction-factor relation"><span>Re · ε / D</span><i>→</i><b>fD</b><i>→</i><span>single pipe</span></div>;
  if (toolId === "pumpSystemHeadPoint") return <div className="mechanical-diagram converter-diagram" role="img" aria-label="Declared system-head curve point relation"><span>Hstatic</span><i>+</i><b>K · Q²</b><i>→</i><span>Hsystem</span></div>;
  if (toolId === "npshAvailableBudget") return <div className="mechanical-diagram converter-diagram" role="img" aria-label="Declared NPSH available head-budget relation"><span>Hsurface + Hsuction</span><i>−</i><b>Hloss + Hvapor</b><i>→</i><span>NPSHa</span></div>;
  if (toolId === "thermalRcStep") return <div className="mechanical-diagram converter-diagram" role="img" aria-label="Declared single RC thermal step response relation"><span>P · R</span><i>×</i><b>1 − e⁻ᵗ⁄ᴿᶜ</b><i>→</i><span>ΔT</span></div>;
  if (toolId === "manningUniformFlow") return <div className="mechanical-diagram converter-diagram" role="img" aria-label="Declared Manning uniform-flow relation"><span>R²⁄³ · S¹⁄²</span><i>÷</i><b>n</b><i>×</i><span>A → Q</span></div>;
  if (toolId === "compressibleMassFlow") return <div className="mechanical-diagram converter-diagram" role="img" aria-label="Declared ideal compressible mass-flow relation"><span>A · pt / √Tt</span><i>×</i><b>γ · R · M</b><i>→</i><span>ṁ</span></div>;
  if (toolId === "machiningTimeBudget") return <div className="mechanical-diagram converter-diagram" role="img" aria-label="Declared cutting-length machining-time relation"><span>Lcut</span><i>÷</i><b>Ffeed</b><i>+</i><span>tallowance</span></div>;
  if (toolId === "threePhasePower") return <div className="mechanical-diagram converter-diagram" role="img" aria-label="Declared three-phase power relation"><span>√3 · VLL · I</span><i>×</i><b>PF</b><i>→</i><span>kVA · kW</span></div>;
  if (toolId === "sheetBendAllowance") return <div className="mechanical-diagram converter-diagram" role="img" aria-label="Declared single-bend allowance relation"><span>θ · π/180</span><i>×</i><b>R + K·T</b><i>→</i><span>BA · BD</span></div>;
  if (toolId === "idealGasEntropyChange") return <div className="mechanical-diagram converter-diagram" role="img" aria-label="Declared ideal-gas entropy-change relation"><span>cp · ln(T₂/T₁)</span><i>−</i><b>R · ln(p₂/p₁)</b><i>→</i><span>Δs</span></div>;
  if (toolId === "bearingAdjustedLife") return <div className="mechanical-diagram converter-diagram" role="img" aria-label="Declared bearing rating-life factors and speed conversion"><span>(C / P)^p</span><i>×</i><b>a1 · a2 · a3</b><i>→</i><span>hours at rpm</span></div>;
  if (toolId === "flywheelEnergy") return <div className="mechanical-diagram converter-diagram" role="img" aria-label="Flywheel rotational inertia and two speed energy states"><span>I · ω1</span><i>→</i><b>½Iω²</b><i>←</i><span>I · ω2</span></div>;
  if (toolId === "frictionClutch") return <div className="mechanical-diagram converter-diagram" role="img" aria-label="Declared friction interface torque relationship"><span>z · μ · Fa</span><i>×</i><b>rm</b><i>→</i><span>Tfriction</span></div>;
  if (toolId === "splineLoad") return <div className="mechanical-diagram converter-diagram" role="img" aria-label="Declared spline torque force and nominal tooth flank pressure relationship"><span>2T / Dp</span><i>÷</i><b>z · ηshare</b><i>→</i><span>Ftooth / flank area</span></div>;
  if (toolId === "gearMeshForce") return <div className="mechanical-diagram converter-diagram" role="img" aria-label="Declared gear torque converted to mesh force components"><span>2T / dp</span><i>→</i><b>Ft</b><i>→</i><span>Fr · Fa · FN</span></div>;
  if (toolId === "beltTension") return <div className="mechanical-diagram converter-diagram" role="img" aria-label="Declared pulley torque converted to belt or chain driving tension"><span>T / rp</span><i>→</i><b>ΔF</b><i>+</i><span>Floose = Ftight</span></div>;
  if (toolId === "vesselGeometry") return <div className="mechanical-diagram converter-diagram" role="img" aria-label="Cylindrical vessel internal volume and shell geometry relation"><span>Di · L</span><i>→</i><b>Vi · Ai</b><i>→</i><span>Vshell</span></div>;
  if (toolId === "threadTensileArea") return <div className="mechanical-diagram converter-diagram" role="img" aria-label="External metric thread tensile stress area relation"><span>D − 0.938194P</span><i>→</i><b>0.7854d²</b><i>→</i><span>At</span></div>;
  if (toolId === "couplingTorsion") return <div className="mechanical-diagram converter-diagram" role="img" aria-label="Declared coupling torque and torsional stiffness relation"><span>T / kt</span><i>→</i><b>θ</b><i>→</i><span>T² / 2kt</span></div>;
  if (toolId === "stability") {
    return <div className="mechanical-diagram stability-diagram" role="img" aria-label="Slender column under central compressive load"><span className="compression top">↓ P</span><i className="column" /><span className="compression bottom">P ↑</span><span className="diagram-label">KL</span></div>;
  }
  if (toolId === "section") {
    const shape = variant ?? "rectangle";
    return <div className={`mechanical-diagram section-diagram section-${shape}`} role="img" aria-label="Cross section about a horizontal centroidal axis"><i /><span className="axis">x</span><span className="axis right">x</span><span className="diagram-label">centroidal axis</span></div>;
  }
  if (toolId === "triangle") {
    return <div className="mechanical-diagram triangle-diagram" role="img" aria-label="Right triangle with two perpendicular legs"><i className="triangle-shape" /><span className="triangle-leg triangle-a">a</span><span className="triangle-leg triangle-b">b</span><span className="triangle-leg triangle-c">c</span><span className="triangle-angle">90°</span></div>;
  }
  if (toolId === "coordinate") {
    return <div className="mechanical-diagram coordinate-diagram" role="img" aria-label="Three-dimensional coordinate frame with two points"><i className="axis-x" /><i className="axis-y" /><i className="axis-z" /><b className="point-a">A</b><b className="point-b">B</b><span className="span-line" /></div>;
  }
  if (toolId === "cylinder") {
    return <div className="mechanical-diagram cylinder-diagram" role="img" aria-label="Right circular cylinder with diameter and length"><i className="cylinder-body" /><i className="cylinder-cap cap-left" /><i className="cylinder-cap cap-right" /><span className="cylinder-label length">L</span><span className="cylinder-label diameter">D</span></div>;
  }
  if (toolId === "density") {
    return <div className="mechanical-diagram density-diagram" role="img" aria-label="Mass occupying a displayed volume"><i className="density-cube" /><span className="density-mass">m</span><span className="density-volume">V</span><span className="density-rho">ρ</span></div>;
  }
  if (toolId === "newton") {
    return <div className="mechanical-diagram newton-diagram" role="img" aria-label="Mass with applied net force and acceleration"><i className="newton-block" /><span className="newton-force">Fnet →</span><span className="newton-accel">a →</span><span className="newton-mass">m</span></div>;
  }
  if (toolId === "kinetic") {
    return <div className="mechanical-diagram kinetic-diagram" role="img" aria-label="Moving mass with speed vector"><i className="kinetic-track" /><i className="kinetic-body" /><span className="kinetic-speed">v →</span><span className="kinetic-mass">m</span><span className="kinetic-energy">½mv²</span></div>;
  }
  if (toolId === "hydrostatic") return <div className="mechanical-diagram fluid-diagram" role="img" aria-label="Static liquid column with vertical depth"><i className="fluid-vessel" /><span className="fluid-surface" /><span className="fluid-depth">h</span><span className="fluid-pressure">ρgh</span></div>;
  if (toolId === "continuity") return <div className="mechanical-diagram continuity-diagram" role="img" aria-label="Two flow sections with differing area and velocity"><i className="continuity-channel" /><span className="continuity-a1">A₁ · v₁ →</span><span className="continuity-a2">→ A₂ · v₂</span><b>Q</b></div>;
  if (toolId === "sensibleHeat") return <div className="mechanical-diagram thermal-diagram" role="img" aria-label="Mass receiving heat and undergoing temperature change"><i className="thermal-mass" /><span className="thermal-heat">Q →</span><span className="thermal-temp">ΔT</span><b>m · c</b></div>;
  if (toolId === "ohm") return <div className="mechanical-diagram circuit-diagram" role="img" aria-label="Ideal DC source connected to one resistor"><i className="circuit-loop" /><i className="circuit-source" /><i className="circuit-resistor" /><span className="circuit-current">I →</span><span className="circuit-voltage">V</span><span className="circuit-r">R</span></div>;
  if (toolId === "fits") return <div className="mechanical-diagram fits-diagram" role="img" aria-label="Hole and shaft tolerance zones relative to a common zero line"><i className="fits-zero" /><span className="fits-hole">HOLE</span><span className="fits-shaft">SHAFT</span><b>zero line</b></div>;
  if (toolId === "toleranceStack") return <div className="mechanical-diagram stack-diagram" role="img" aria-label="Three linear tolerance contributors in a dimensional chain"><i className="stack-line" /><span>±t₁</span><span>±t₂</span><span>±t₃</span><b>N</b></div>;
  if (toolId === "toleranceSampling") return <div className="mechanical-diagram converter-diagram" role="img" aria-label="Seeded uniform tolerance-contributor sample relationship"><span>N · ±t₁…±t₆</span><i>→</i><b>seeded draws</b><i>→</i><span>sample spread</span></div>;
  if (toolId === "taylorToolLife") return <div className="mechanical-diagram converter-diagram" role="img" aria-label="Taylor cutting speed and tool-life relation"><span>V</span><i>×</i><b>Tⁿ</b><i>→</i><span>C</span></div>;
  if (toolId === "cuttingForce") return <div className="mechanical-diagram converter-diagram" role="img" aria-label="Specific cutting force and uncut-chip area relationship"><span>kc · ap · f</span><i>→</i><b>Fc</b><i>× Vc →</i><span>Pideal</span></div>;
  if (toolId === "weldGroup") return <div className="mechanical-diagram converter-diagram" role="img" aria-label="Symmetric two-line weld group direct and torsional line-load relationship"><span>F / 2L</span><i>+</i><b>M·r / Ju</b><i>→</i><span>line load</span></div>;
  if (toolId === "position") return <div className="mechanical-diagram position-diagram" role="img" aria-label="Two-dimensional true position screen with a measured center offset"><i className="position-zone" /><i className="position-cross" /><b className="position-actual">●</b><span>Δx · Δy</span></div>;
  if (toolId === "mmc") return <div className="mechanical-diagram mmc-diagram" role="img" aria-label="Cylindrical feature of size with MMC and virtual condition boundaries"><i className="mmc-boundary outer" /><i className="mmc-boundary inner" /><b>MMC</b><span>VC</span></div>;
  if (toolId === "motionProfile") return <div className="mechanical-diagram motion-diagram" role="img" aria-label="Trapezoidal velocity profile with acceleration, cruise, and deceleration phases"><i className="motion-profile" /><span>ta</span><span>tc</span><span>ta</span><b>vmax</b></div>;
  if (toolId === "reflectedInertia") return <div className="mechanical-diagram inertia-diagram" role="img" aria-label="Load inertia reflected through a reduction gear to a motor"><i className="inertia-load" /><i className="inertia-gear" /><i className="inertia-motor" /><span>JL</span><span>N:1</span><b>JM</b></div>;
  if (toolId === "pneumatic") return <div className="mechanical-diagram pneumatic-diagram" role="img" aria-label="Pneumatic cylinder with bore, rod, and pressure"><i className="pneumatic-body" /><i className="pneumatic-rod" /><span>P</span><b>D</b><em>d</em></div>;
  if (toolId === "clampForce") return <div className="mechanical-diagram clamp-diagram" role="img" aria-label="Single linkage force transfer angle"><i className="clamp-arm" /><i className="clamp-link" /><b>F</b><span>θ</span><em>Ftransfer</em></div>;
  if (toolId === "torsion") return <div className="mechanical-diagram converter-diagram" role="img" aria-label="Circular shaft under torsion"><span>T</span><i>→</i><b>τ · θ</b><i>→</i><span>J · G · L</span></div>;
  if (toolId === "bearingLife") return <div className="mechanical-diagram converter-diagram" role="img" aria-label="Basic bearing rating-life relation"><span>C / P</span><i>→</i><b>(C/P)ᵖ</b><i>→</i><span>L10</span></div>;
  if (toolId === "boltPreload") return <div className="mechanical-diagram converter-diagram" role="img" aria-label="Torque-preload nut-factor relation"><span>T</span><i>÷</i><b>K · d</b><i>→</i><span>Fp</span></div>;
  if (toolId === "millingMrr") return <div className="mechanical-diagram converter-diagram" role="img" aria-label="Milling material-removal-rate relation"><span>ae · ap</span><i>×</i><b>vf</b><i>→</i><span>MRR</span></div>;
  if (toolId === "lmtd") return <div className="mechanical-diagram converter-diagram" role="img" aria-label="Logarithmic mean temperature difference"><span>ΔT₁ · ΔT₂</span><i>→</i><b>LMTD</b><i>×</i><span>U · A</span></div>;
  if (toolId === "darcy") return <div className="mechanical-diagram converter-diagram" role="img" aria-label="Darcy–Weisbach major head loss"><span>f · L/D</span><i>×</i><b>ρv²/2</b><i>→</i><span>Δp</span></div>;
  if (toolId === "thermalExpansion") return <div className="mechanical-diagram converter-diagram" role="img" aria-label="Free linear thermal expansion relationship"><span>L₀ · α</span><i>→</i><b>ΔT</b><i>→</i><span>ΔL</span></div>;
  if (toolId === "thermalStress") return <div className="mechanical-diagram converter-diagram" role="img" aria-label="Fully restrained thermal stress relationship"><span>E · α</span><i>→</i><b>ΔT</b><i>→</i><span>σth</span></div>;
  if (toolId === "planeConduction") return <div className="mechanical-diagram converter-diagram" role="img" aria-label="One-dimensional plane-wall conduction relationship"><span>Th</span><i>→</i><b>kA / L</b><i>→</i><span>Tc</span></div>;
  if (toolId === "bernoulli") return <div className="mechanical-diagram converter-diagram" role="img" aria-label="Two-station ideal flow energy relationship"><span>p₁ · v₁ · z₁</span><i>→</i><b>ideal flow</b><i>→</i><span>p₂ · v₂ · z₂</span></div>;
  if (toolId === "combinedStress") return <div className="mechanical-diagram converter-diagram" role="img" aria-label="Plane-stress superposition relationship"><span>σa + σb</span><i>→</i><b>τxy</b><i>→</i><span>σ₁ · σvm</span></div>;
  if (toolId === "thinVessel") return <div className="mechanical-diagram converter-diagram" role="img" aria-label="Closed thin-wall cylindrical vessel stress relationship"><span>p · D</span><i>→</i><b>2t / 4t</b><i>→</i><span>σhoop · σlong</span></div>;
  if (toolId === "leadScrew") return <div className="mechanical-diagram converter-diagram" role="img" aria-label="Ideal lead-screw force and travel relationship"><span>F · lead</span><i>→</i><b>2πη</b><i>→</i><span>T · v</span></div>;
  if (toolId === "airConsumption") return <div className="mechanical-diagram converter-diagram" role="img" aria-label="Double-acting pneumatic-cylinder air-consumption relationship"><span>A · stroke</span><i>→</i><b>Pabs</b><i>→</i><span>free air</span></div>;
  if (toolId === "gearRatio") return <div className="mechanical-diagram converter-diagram" role="img" aria-label="Ideal gear-pair speed and torque relationship"><span>z₁ · n₁</span><i>→</i><b>z₂ · η</b><i>→</i><span>n₂ · T₂</span></div>;
  if (toolId === "boltLoad") return <div className="mechanical-diagram converter-diagram" role="img" aria-label="Single-bolt nominal load and stress relationship"><span>Ft · Fs</span><i>→</i><b>πd²/4</b><i>→</i><span>σ · τ</span></div>;
  if (toolId === "safetyMargin") return <div className="mechanical-diagram converter-diagram" role="img" aria-label="User-entered allowable stress comparison"><span>σallow</span><i>→</i><b>σapp</b><i>→</i><span>factor · margin</span></div>;
  if (toolId === "circularArc") return <div className="mechanical-diagram converter-diagram" role="img" aria-label="Circular arc and segment geometry"><span>r · θ</span><i>→</i><b>circle</b><i>→</i><span>arc · chord</span></div>;
  if (toolId === "compressionSpring") return <div className="mechanical-diagram converter-diagram" role="img" aria-label="Elementary close-coiled compression-spring relationship"><span>G · d⁴</span><i>→</i><b>8D³Na</b><i>→</i><span>k · F</span></div>;
  if (toolId === "drillingTime") return <div className="mechanical-diagram converter-diagram" role="img" aria-label="Drilling cutting speed, feed, and time relationship"><span>Dc · n</span><i>→</i><b>fr</b><i>→</i><span>vc · vf · Tc</span></div>;
  if (toolId === "turningMrr") return <div className="mechanical-diagram converter-diagram" role="img" aria-label="Theoretical turning material-removal relationship"><span>ap · f</span><i>→</i><b>Vc</b><i>→</i><span>MRR</span></div>;
  if (toolId === "processCapability") return <div className="mechanical-diagram converter-diagram" role="img" aria-label="Process capability specification comparison"><span>LSL · USL</span><i>→</i><b>6σ</b><i>→</i><span>Cp · Cpk</span></div>;
  if (toolId === "extensionSpring") return <div className="mechanical-diagram converter-diagram" role="img" aria-label="Extension spring force relationship"><span>Fi</span><i>+</i><b>k · x</b><i>→</i><span>F</span></div>;
  if (toolId === "torsionSpring") return <div className="mechanical-diagram converter-diagram" role="img" aria-label="Helical torsion spring rate and moment relationship"><span>E · d⁴</span><i>→</i><b>kθ · θ</b><i>→</i><span>M · σ</span></div>;
  if (toolId === "keyway") return <div className="mechanical-diagram converter-diagram" role="img" aria-label="Parallel key torque transfer and nominal stress relationship"><span>T · D</span><i>→</i><b>Ft</b><i>→</i><span>τkey · σbearing</span></div>;
  if (toolId === "cuttingParameters") return <div className="mechanical-diagram converter-diagram" role="img" aria-label="Milling cutting condition and power relationship"><span>vc · Dc</span><i>→</i><b>n · fz · z</b><i>→</i><span>vf · MRR · Pc</span></div>;
  if (toolId === "sheetMetalBend") return <div className="mechanical-diagram converter-diagram" role="img" aria-label="Sheet-metal bend allowance and developed length relationship"><span>B · IR · K</span><i>→</i><b>BA · BD</b><i>→</i><span>flat length</span></div>;
  if (toolId === "productionMetrics") return <div className="mechanical-diagram converter-diagram" role="img" aria-label="Production time, count, and OEE relationship"><span>PPT · ST</span><i>→</i><b>A · P · Q</b><i>→</i><span>OEE · takt</span></div>;
  if (toolId === "gageRr") return <div className="mechanical-diagram converter-diagram" role="img" aria-label="Balanced crossed Gauge R and R study relationship"><span>2 operators</span><i>×</i><b>2 parts · 2 trials</b><i>→</i><span>ANOVA variance</span></div>;
  if (toolId === "gaugeBiasStudy") return <div className="mechanical-diagram converter-diagram" role="img" aria-label="Declared reference and observed measurement study arithmetic"><span>xref · ȳ</span><i>→</i><b>bias</b><i>→</i><span>span over points</span></div>;
  if (toolId === "controlChart") return <div className="mechanical-diagram converter-diagram" role="img" aria-label="Shewhart center-line and upper-lower-limit arithmetic"><span>x̄ · R / s / MR</span><i>→</i><b>CL · UCL · LCL</b><i>→</i><span>declared series</span></div>;
  if (toolId === "measurementUncertainty") return <div className="mechanical-diagram converter-diagram" role="img" aria-label="Independent standard uncertainty and expanded uncertainty relationship"><span>uA · uCal · uRes</span><i>→</i><b>uc</b><i>× k →</i><span>U</span></div>;
  if (toolId === "thermalRadiation") return <div className="mechanical-diagram converter-diagram" role="img" aria-label="Gray-surface radiation exchange relationship"><span>ε · A · Ts</span><i>→</i><b>σ(Ts⁴−Tsur⁴)</b><i>→</i><span>qrad</span></div>;
  if (toolId === "shaftDesign") return <div className="mechanical-diagram converter-diagram" role="img" aria-label="Solid shaft torsion stiffness and critical speed relationship"><span>T · d · L</span><i>→</i><b>τ · θ · δ</b><i>→</i><span>n₁</span></div>;
  if (toolId === "bearingLoad") return <div className="mechanical-diagram converter-diagram" role="img" aria-label="Bearing equivalent load and rating relationship"><span>XFr · YFa</span><i>→</i><b>P · Creq</b><i>→</i><span>C0/P0 · DN</span></div>;
  if (toolId === "formControl") return <div className="mechanical-diagram converter-diagram" role="img" aria-label="Measured extrema form-control screening relationship"><span>xmin</span><i>→</i><b>xmax − xmin</b><i>→</i><span>observed span</span></div>;
  if (toolId === "driveRatio") return <div className="mechanical-diagram converter-diagram" role="img" aria-label="Ideal drive speed torque and force relationship"><span>N₁ · N₂ · T₁</span><i>→</i><b>i · n₂ · T₂</b><i>→</i><span>Ft · Fr · Fa</span></div>;
  if (toolId === "motionDuty") return <div className="mechanical-diagram converter-diagram" role="img" aria-label="Motion duty acceleration RMS torque and energy relationship"><span>J · ω · t</span><i>→</i><b>α · Tacc</b><i>→</i><span>Trms · E</span></div>;
  if (toolId === "filletWeld") return <div className="mechanical-diagram converter-diagram" role="img" aria-label="Fillet weld throat stress and heat input relationship"><span>a · L · n</span><i>→</i><b>0.707a · Aeff · τ</b><i>→</i><span>V · I · v</span></div>;
  if (toolId === "threadDesign") return <div className="mechanical-diagram converter-diagram" role="img" aria-label="Thread pilot hole engagement and reviewed root-shear screening relationship"><span>Dmajor · P · E</span><i>→</i><b>Dtap · Ats</b><i>→</i><span>n · Le · Ds · En</span></div>;
  if (toolId === "orificeFlow") return <div className="mechanical-diagram converter-diagram" role="img" aria-label="Incompressible orifice pressure-drop flow relationship"><span>Cd · D2 · ρ</span><i>→</i><b>Δp · β</b><i>→</i><span>Q · ṁ</span></div>;
  if (toolId === "dimensionCheck") return <div className="mechanical-diagram converter-diagram" role="img" aria-label="SI base-dimension vector consistency relationship"><span>[M L T I Θ N J]ₗ</span><i>→</i><b>Δ vector</b><i>→</i><span>[M L T I Θ N J]ᵣ</span></div>;
  if (toolId === "shaftCombined") return <div className="mechanical-diagram converter-diagram" role="img" aria-label="Solid circular shaft bending and torsion point-stress relationship"><span>M · T · d</span><i>→</i><b>σb · τt</b><i>→</i><span>σ1 · σvm</span></div>;
  if (toolId === "mohrCircle") return <div className="mechanical-diagram converter-diagram" role="img" aria-label="Plane-stress Mohr’s Circle transformation relationship"><span>σx · σy · τxy</span><i>→</i><b>σavg · R</b><i>→</i><span>σ1 · σ2 · θp</span></div>;
  if (toolId === "pressFit") return <div className="mechanical-diagram converter-diagram" role="img" aria-label="Simplified interference press-fit contact and friction relationship"><span>Ds − Di · Do</span><i>→</i><b>p · μ</b><i>→</i><span>Fhold · Thold</span></div>;
  if (toolId === "jointSeparation") return <div className="mechanical-diagram converter-diagram" role="img" aria-label="Parallel-spring bolted-joint separation relationship"><span>Fp · kb · km</span><i>→</i><b>C · P</b><i>→</i><span>Fm · Psep</span></div>;
  if (toolId === "hydraulicCylinder") return <div className="mechanical-diagram converter-diagram" role="img" aria-label="Ideal double-acting hydraulic-cylinder force speed and travel relationship"><span>D · d · p</span><i>→</i><b>A · F · Q</b><i>→</i><span>v · t</span></div>;
  if (toolId === "hydraulicPump") return <div className="mechanical-diagram converter-diagram" role="img" aria-label="Positive-displacement hydraulic-pump flow power and torque relationship"><span>Vd · n · Δp</span><i>→</i><b>Q · η</b><i>→</i><span>P · T</span></div>;
  if (toolId === "hydraulicMotor") return <div className="mechanical-diagram converter-diagram" role="img" aria-label="Positive-displacement hydraulic-motor torque speed and power relationship"><span>Vd · Δp · Q</span><i>→</i><b>T · n · η</b><i>→</i><span>Pshaft</span></div>;
  if (toolId === "hydraulicLine") return <div className="mechanical-diagram converter-diagram" role="img" aria-label="Circular hydraulic-line flow area and mean-velocity relationship"><span>Q · Di</span><i>→</i><b>A</b><i>→</i><span>vmean / vref</span></div>;
  if (toolId === "orientationControl") return <div className="mechanical-diagram converter-diagram" role="img" aria-label="GD&T orientation extrema variation relationship"><span>datum setup · rmin</span><i>→</i><b>rmax − rmin</b><i>→</i><span>variation / T</span></div>;
  if (toolId === "profileRunout") return <div className="mechanical-diagram converter-diagram" role="img" aria-label="Profile or runout indicator extrema variation relationship"><span>fixture · rmin</span><i>→</i><b>rmax − rmin</b><i>→</i><span>variation / T</span></div>;
  if (toolId === "processPerformance") return <div className="mechanical-diagram converter-diagram" role="img" aria-label="Overall process performance relationship"><span>LSL · x̄ · USL</span><i>→</i><b>soverall</b><i>→</i><span>Pp · Ppk</span></div>;
  if (toolId === "ballScrewSizing") return <div className="mechanical-diagram converter-diagram" role="img" aria-label="Ball screw force lead speed and torque relationship"><span>Fa · P · η</span><i>→</i><b>T · n</b><i>→</i><span>v · Pmech</span></div>;
  if (toolId === "rackPinion") return <div className="mechanical-diagram converter-diagram" role="img" aria-label="Rack and pinion horizontal feed force torque and speed relationship"><span>m · μ · a · Fe</span><i>→</i><b>Fr · dp</b><i>→</i><span>T · n · P</span></div>;
  if (toolId === "beltAxis") return <div className="mechanical-diagram converter-diagram" role="img" aria-label="Horizontal belt axis guide friction force pulley torque and speed relationship"><span>m · μ · dp</span><i>→</i><b>Fa · η</b><i>→</i><span>T · n · P</span></div>;
  if (toolId === "cuttingPower") return <div className="mechanical-diagram converter-diagram" role="img" aria-label="Turning cutting power relationship"><span>ap · f · vc</span><i>→</i><b>Kc · η</b><i>→</i><span>Pc · Pmachine</span></div>;
  if (toolId === "drillPointDepth") return <div className="mechanical-diagram converter-diagram" role="img" aria-label="Conical drill point depth relationship"><span>D · θ</span><i>→</i><b>hpoint</b><i>→</i><span>hprogram</span></div>;
  if (toolId === "toolDeflection") return <div className="mechanical-diagram converter-diagram" role="img" aria-label="Circular cantilever tool deflection relationship"><span>F · L · d</span><i>→</i><b>E · I</b><i>→</i><span>δ · σ</span></div>;
  if (toolId === "fatigueConcentration") return <div className="mechanical-diagram converter-diagram" role="img" aria-label="Fatigue stress concentration relationship"><span>Kt · q</span><i>→</i><b>Kf</b><i>→</i><span>σeffective</span></div>;
  if (toolId === "goodmanFatigue") return <div className="mechanical-diagram converter-diagram" role="img" aria-label="Goodman fatigue utilization relationship"><span>σa · σm · Kf</span><i>→</i><b>Sn · Su</b><i>→</i><span>U</span></div>;
  if (toolId === "minerDamage") return <div className="mechanical-diagram converter-diagram" role="img" aria-label="Miner cumulative damage relationship"><span>n1/N1 · n2/N2</span><i>→</i><b>n3/N3</b><i>→</i><span>D</span></div>;
  if (toolId === "planetaryGear") return <div className="mechanical-diagram converter-diagram" role="img" aria-label="Fixed ring planetary gear ratio relationship"><span>Ns · Nr · P</span><i>→</i><b>i · Np</b><i>→</i><span>ncarrier · Tcarrier</span></div>;
  if (toolId === "wormDrive") return <div className="mechanical-diagram converter-diagram" role="img" aria-label="Ideal worm drive reduction relationship"><span>Zw · S</span><i>→</i><b>i · η</b><i>→</i><span>nout · Tout</span></div>;
  if (toolId === "sCurveProfile") return <div className="mechanical-diagram converter-diagram" role="img" aria-label="Symmetric jerk-percent S-curve timing relationship"><span>d · vmax · aavg</span><i>→</i><b>J% · apeak</b><i>→</i><span>tacc · tcruise</span></div>;
  if (toolId === "torqueSpeedDuty") return <div className="mechanical-diagram converter-diagram" role="img" aria-label="Torque speed duty-point relationship"><span>J · Δn · ta</span><i>→</i><b>Tacc + Tload</b><i>→</i><span>P · margin</span></div>;
  if (toolId === "fixtureClamping") return <div className="mechanical-diagram converter-diagram" role="img" aria-label="Friction-only fixture clamping relationship"><span>Fcut · M</span><i>→</i><b>μ · N</b><i>→</i><span>Ffriction</span></div>;
  if (toolId === "pickPlaceCycle") return <div className="mechanical-diagram converter-diagram" role="img" aria-label="Repeated pick and place timing relationship"><span>tout · tback</span><i>→</i><b>tpick · tplace</b><i>→</i><span>tcycle · N</span></div>;
  if (toolId === "payloadInertia") return <div className="mechanical-diagram converter-diagram" role="img" aria-label="Point-mass payload inertia relationship"><span>me + mp</span><i>→</i><b>r</b><i>→</i><span>m r²</span></div>;
  if (toolId === "pneumaticCycleTime") return <div className="mechanical-diagram converter-diagram" role="img" aria-label="Actual-flow pneumatic cylinder extend and retract timing relationship"><span>D · d · L</span><i>→</i><b>A · Qactual</b><i>→</i><span>vextend · tretract</span></div>;
  if (toolId === "valveCv") return <div className="mechanical-diagram converter-diagram" role="img" aria-label="Liquid water Cv pressure drop and flow relationship"><span>Cv · ΔP</span><i>→</i><b>SG</b><i>→</i><span>Qliquid</span></div>;
  if (toolId === "vacuumHolding") return <div className="mechanical-diagram converter-diagram" role="img" aria-label="Declared vacuum holding load-case relationship"><span>m · g · a</span><i>→</i><b>μ · M</b><i>→</i><span>FTH</span></div>;
  if (toolId === "additiveBuild") return <div className="mechanical-diagram converter-diagram" role="img" aria-label="Declared additive material time and direct-cost relationship"><span>V · ρ · s</span><i>→</i><b>R · rates</b><i>→</i><span>m · t · C</span></div>;
  if (toolId === "gravityMoment") return <div className="mechanical-diagram converter-diagram" role="img" aria-label="Static gravity moment about a planar pivot relationship"><span>m · g · r</span><i>→</i><b>sin θ</b><i>→</i><span>Mg · Mres</span></div>;
  if (toolId === "pitchCircle") return <div className="mechanical-diagram converter-diagram" role="img" aria-label="Equal-spacing pitch-circle coordinate geometry"><span>PCD · n · θ₀</span><i>→</i><b>Δθ · r</b><i>→</i><span>xᵢ · yᵢ · chord</span></div>;
  if (toolId === "regularPolygon") return <div className="mechanical-diagram converter-diagram" role="img" aria-label="Regular-polygon side-count geometry"><span>n · s</span><i>→</i><b>a · R · P</b><i>→</i><span>angle · area</span></div>;
  if (toolId === "eccentricBoltGroup") return <div className="mechanical-diagram converter-diagram" role="img" aria-label="Concentric circular bolt-group direct and torsional shear"><span>F · e · n</span><i>→</i><b>M · r · Σr²</b><i>→</i><span>Vdirect · Vtorsion</span></div>;
  if (toolId === "pinStress") return <div className="mechanical-diagram converter-diagram" role="img" aria-label="Pin nominal shear and projected bearing stress"><span>F · n · planes</span><i>→</i><b>πd²/4 · dt</b><i>→</i><span>τpin · σbearing</span></div>;
  if (toolId === "gearToothStress") return <div className="mechanical-diagram converter-diagram" role="img" aria-label="Static Lewis-type spur or parallel-axis helical gear tooth root stress"><span>Ft · β · z</span><i>→</i><b>Fb · zv · mY</b><i>→</i><span>σF</span></div>;
  if (toolId === "vacuumEvacuation") return <div className="mechanical-diagram converter-diagram" role="img" aria-label="Ideal constant-effective-speed vacuum evacuation relationship"><span>V · S</span><i>→</i><b>ln(p₁/p₂)</b><i>→</i><span>t · Srequired</span></div>;
  if (toolId === "toggleForce") return <div className="mechanical-diagram converter-diagram" role="img" aria-label="Symmetric two-link pre-dead-centre toggle-force relationship"><span>Fᵢₙ · θ</span><i>→</i><b>1/[2tanθ]</b><i>→</i><span>MA · Fₒᵤₜ</span></div>;
  if (toolId === "wristInertia") return <div className="mechanical-diagram converter-diagram" role="img" aria-label="Declared one-axis wrist inertia parallel-axis relation"><span>Icg · m · r</span><i>→</i><b>Icg + mr²</b><i>→</i><span>Iwrist</span></div>;
  if (toolId === "cycleBuilder") return <div className="mechanical-diagram converter-diagram" role="img" aria-label="Ordered serial machine cycle-time sum"><span>t₁ + t₂ + … + t₆</span><i>→</i><b>Σti</b><i>→</i><span>cycle · throughput</span></div>;
  if (toolId === "pneumaticLineLoss") return <div className="mechanical-diagram converter-diagram" role="img" aria-label="Low-pressure pneumatic straight-pipe Darcy loss"><span>Q · D · L</span><i>→</i><b>fρv²/2</b><i>→</i><span>Δp · Δp/p₁</span></div>;
  if (toolId === "tappingTorque") return <div className="mechanical-diagram converter-diagram" role="img" aria-label="User coefficient tapping torque and spindle power"><span>k · d · e</span><i>→</i><b>k·d³·e</b><i>→</i><span>T · P</span></div>;
  if (toolId === "threadMachiningTime") return <div className="mechanical-diagram converter-diagram" role="img" aria-label="Declared thread pitch feed and repeated travel time"><span>p · n · L</span><i>→</i><b>L/(p·n)</b><i>→</i><span>tpass · ttotal</span></div>;
  if (toolId === "reynoldsNumber") return <div className="mechanical-diagram converter-diagram" role="img" aria-label="Declared density velocity hydraulic diameter and viscosity Reynolds-number calculation"><span>ρ · u · Dh</span><i>→</i><b>ρuDh/μ</b><i>→</i><span>Re · ratio</span></div>;
  if (toolId === "minorLosses") return <div className="mechanical-diagram converter-diagram" role="img" aria-label="Declared aggregate loss coefficient pressure loss calculation"><span>ΣK · ρ · v</span><i>→</i><b>ΣKρv²/2</b><i>→</i><span>Δp · h</span></div>;
  if (toolId === "pipeSizing") return <div className="mechanical-diagram converter-diagram" role="img" aria-label="Declared flow and target velocity circular pipe diameter calculation"><span>Q · vtarget</span><i>→</i><b>4Q/(πv)</b><i>→</i><span>A · D</span></div>;
  if (toolId === "buoyancyForce") return <div className="mechanical-diagram converter-diagram" role="img" aria-label="Declared displaced-volume buoyancy and weight force comparison"><span>ρf · Vd</span><i>→</i><b>ρfgVd</b><i>↔</i><span>W · Fnet</span></div>;
  if (toolId === "submergedPlane") return <div className="mechanical-diagram converter-diagram" role="img" aria-label="Fully submerged vertical rectangle resultant and center of pressure"><span>ρ · yc · A</span><i>→</i><b>F · Ix</b><i>→</i><span>yCP</span></div>;
  if (toolId === "convectionHeat") return <div className="mechanical-diagram converter-diagram" role="img" aria-label="Declared convection coefficient area and temperature-difference heat-rate calculation"><span>h · A · ΔT</span><i>→</i><b>hAΔT</b><i>→</i><span>Q̇ · hA</span></div>;
  if (toolId === "thermalResistance") return <div className="mechanical-diagram converter-diagram" role="img" aria-label="Declared series convection wall contact and convection thermal resistance network"><span>Rconv,h · Rwall</span><i>+</i><b>Rc + Rconv,c</b><i>→</i><span>Rtotal · ΔT</span></div>;
  if (toolId === "idealGas") return <div className="mechanical-diagram converter-diagram" role="img" aria-label="Declared ideal gas pressure volume temperature and molar mass calculation"><span>p · V · T · M</span><i>→</i><b>pV = nRuT</b><i>→</i><span>ρ · m · n</span></div>;
  if (toolId === "isentropicMachine") return <div className="mechanical-diagram converter-diagram" role="img" aria-label="Declared isentropic pressure ratio temperature and work calculation"><span>p1 · T1 · γ</span><i>→</i><b>T2s/T1</b><i>→</i><span>w · P · ηis</span></div>;
  if (toolId === "arithmeticScratchpad") return <div className="mechanical-diagram converter-diagram" role="img" aria-label="Fixed scalar arithmetic grammar relationship"><span>numbers · ( )</span><i>→</i><b>+ − × ÷ ^</b><i>→</i><span>declared result</span></div>;
  return <div className="mechanical-diagram converter-diagram" role="img" aria-label="Quantity converted through canonical SI"><span>display</span><i>→</i><b>SI</b><i>→</i><span>display</span></div>;
}
