/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AtlasRouteImport } from './routes/atlas'
import { Route as FeedbackRouteImport } from './routes/feedback'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as ReferenceRouteImport } from './routes/reference'
import { Route as ReviewRouteImport } from './routes/review'
import { Route as StudioRouteImport } from './routes/studio'
import { Route as WorkshopRouteImport } from './routes/workshop'
import { Route as CSlugRouteImport } from './routes/c.$slug'
import { Route as StudioIndexRouteImport } from './routes/studio.index'
import { Route as StudioIdRouteImport } from './routes/studio.$id'
import { Route as ToolToolIdRouteImport } from './routes/tool/$toolId'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AtlasRoute = AtlasRouteImport.update({
  id: '/atlas',
  path: '/atlas',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedbackRoute = FeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferenceRoute = ReferenceRouteImport.update({
  id: '/reference',
  path: '/reference',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewRoute = ReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioRoute = StudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkshopRoute = WorkshopRouteImport.update({
  id: '/workshop',
  path: '/workshop',
  getParentRoute: () => rootRouteImport,
} as any)
const CSlugRoute = CSlugRouteImport.update({
  id: '/c/$slug',
  path: '/c/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioIndexRoute = StudioIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StudioRoute,
} as any)
const StudioIdRoute = StudioIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => StudioRoute,
} as any)
const ToolToolIdRoute = ToolToolIdRouteImport.update({
  id: '/tool/$toolId',
  path: '/tool/$toolId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/atlas': typeof AtlasRoute
  '/feedback': typeof FeedbackRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/projects': typeof ProjectsRoute
  '/reference': typeof ReferenceRoute
  '/review': typeof ReviewRoute
  '/studio': typeof StudioRouteWithChildren
  '/workshop': typeof WorkshopRoute
  '/c/$slug': typeof CSlugRoute
  '/studio/$id': typeof StudioIdRoute
  '/tool/$toolId': typeof ToolToolIdRoute
  '/studio/': typeof StudioIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/atlas': typeof AtlasRoute
  '/feedback': typeof FeedbackRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/projects': typeof ProjectsRoute
  '/reference': typeof ReferenceRoute
  '/review': typeof ReviewRoute
  '/workshop': typeof WorkshopRoute
  '/c/$slug': typeof CSlugRoute
  '/studio/$id': typeof StudioIdRoute
  '/tool/$toolId': typeof ToolToolIdRoute
  '/studio': typeof StudioIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/atlas': typeof AtlasRoute
  '/feedback': typeof FeedbackRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/projects': typeof ProjectsRoute
  '/reference': typeof ReferenceRoute
  '/review': typeof ReviewRoute
  '/studio': typeof StudioRouteWithChildren
  '/workshop': typeof WorkshopRoute
  '/c/$slug': typeof CSlugRoute
  '/studio/$id': typeof StudioIdRoute
  '/tool/$toolId': typeof ToolToolIdRoute
  '/studio/': typeof StudioIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/atlas'
    | '/feedback'
    | '/library'
    | '/login'
    | '/projects'
    | '/reference'
    | '/review'
    | '/studio'
    | '/workshop'
    | '/c/$slug'
    | '/studio/$id'
    | '/tool/$toolId'
    | '/studio/'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/atlas'
    | '/feedback'
    | '/library'
    | '/login'
    | '/projects'
    | '/reference'
    | '/review'
    | '/workshop'
    | '/c/$slug'
    | '/studio/$id'
    | '/tool/$toolId'
    | '/studio'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/atlas'
    | '/feedback'
    | '/library'
    | '/login'
    | '/projects'
    | '/reference'
    | '/review'
    | '/studio'
    | '/workshop'
    | '/c/$slug'
    | '/studio/$id'
    | '/tool/$toolId'
    | '/studio/'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AtlasRoute: typeof AtlasRoute
  FeedbackRoute: typeof FeedbackRoute
  LibraryRoute: typeof LibraryRoute
  LoginRoute: typeof LoginRoute
  ProjectsRoute: typeof ProjectsRoute
  ReferenceRoute: typeof ReferenceRoute
  ReviewRoute: typeof ReviewRoute
  StudioRoute: typeof StudioRouteWithChildren
  WorkshopRoute: typeof WorkshopRoute
  CSlugRoute: typeof CSlugRoute
  ToolToolIdRoute: typeof ToolToolIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atlas': {
      id: '/atlas'
      path: '/atlas'
      fullPath: '/atlas'
      preLoaderRoute: typeof AtlasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feedback': {
      id: '/feedback'
      path: '/feedback'
      fullPath: '/feedback'
      preLoaderRoute: typeof FeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reference': {
      id: '/reference'
      path: '/reference'
      fullPath: '/reference'
      preLoaderRoute: typeof ReferenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review': {
      id: '/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof ReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workshop': {
      id: '/workshop'
      path: '/workshop'
      fullPath: '/workshop'
      preLoaderRoute: typeof WorkshopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$slug': {
      id: '/c/$slug'
      path: '/c/$slug'
      fullPath: '/c/$slug'
      preLoaderRoute: typeof CSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio/': {
      id: '/studio/'
      path: '/'
      fullPath: '/studio/'
      preLoaderRoute: typeof StudioIndexRouteImport
      parentRoute: typeof StudioRoute
    }
    '/studio/$id': {
      id: '/studio/$id'
      path: '/$id'
      fullPath: '/studio/$id'
      preLoaderRoute: typeof StudioIdRouteImport
      parentRoute: typeof StudioRoute
    }
    '/tool/$toolId': {
      id: '/tool/$toolId'
      path: '/tool/$toolId'
      fullPath: '/tool/$toolId'
      preLoaderRoute: typeof ToolToolIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface StudioRouteChildren {
  StudioIdRoute: typeof StudioIdRoute
  StudioIndexRoute: typeof StudioIndexRoute
}

const StudioRouteChildren: StudioRouteChildren = {
  StudioIdRoute: StudioIdRoute,
  StudioIndexRoute: StudioIndexRoute,
}

const StudioRouteWithChildren =
  StudioRoute._addFileChildren(StudioRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AtlasRoute: AtlasRoute,
  FeedbackRoute: FeedbackRoute,
  LibraryRoute: LibraryRoute,
  LoginRoute: LoginRoute,
  ProjectsRoute: ProjectsRoute,
  ReferenceRoute: ReferenceRoute,
  ReviewRoute: ReviewRoute,
  StudioRoute: StudioRouteWithChildren,
  WorkshopRoute: WorkshopRoute,
  CSlugRoute: CSlugRoute,
  ToolToolIdRoute: ToolToolIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
